### ISSUE TITLE
Feature request: Change Wallpaper in context menu

### ISSUE THREAD

**Issue by jlnr** [spheras/desktopfolder#110]
Since this app adds a context menu to the desktop, it would be nice to have a link to `settings://desktop` in there, to quickly change the wallpaper. Right-clicking a thing to edit it is a common pattern, so I think this would be an intuitive position for this shortcut.

(I've tried `xdg-open settings://desktop` and it did the right thing on Juno; not sure if that URL already worked on Loki.)

**Comment by spheras** [comment]
yes, seems reasonable. I'll try.  Thanks @jlnr

**Comment by spheras** [comment]
I made an option in the context menu that appears when you right click the desktop: "change wallpaper", calling to the "xdg-open settings://desktop".  Thanks @jlnr

**Comment by jlnr** [comment]
Thanks! Works like a charm.
