### ISSUE TITLE
UX: Catch duplicate names earlier

### ISSUE THREAD

**Issue by jlnr** [spheras/desktopfolder#112]
When I create a new panel with the default name, and then try to create another panel with the default name, I get an error dialog because duplicate names aren't allowed.

Suggestions:

1. Don't pre-populate the text field with a name that won't work, automatically append a "2" or so.
2. And/or don't allow the user to press "OK" if the name is a duplicate, instead disable the button and display an error inline.
3. And/or don't simply give up after showing the error message, but re-open the dialog so that I can try another name. Chances are I still want to create that note or folder :)

Ran into this while trying to reproduce #111. Probably not a thing that people will hit super often.

**Comment by spheras** [comment]
mmm Ok. I think I can improve easily it. I will try.  Thanks!

**Comment by spheras** [comment]
I added some code to fix this beahviour. Thanks!
