### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [spheras/desktopfolder#113]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by ItsPossibleAlready** [comment]
Why are you need flatpak version? It doesn't normally work on gnome(just download another extension for gnome shell). Or maby eOS Loki to get new versions, but css was changed on gtk 3.22 and again it doesn't work normally. Or you are waiting juno, wait over month, developer is hardly work for this.

**Comment by spheras** [comment]
thanks @LeandroStanger. This issue is related to #9.  This issue (snap/flatpack) is a bit freezed, but maybe someone in the future will get the info.  Thanks!!

**Comment by spheras** [comment]
@ItsPossibleAlready, thanks for your comments. Yes, now is not an urgent issue, but in my opinion could be a a good feature for the future if someone is interested.

**Comment by spheras** [comment]
I will close this issue, and continue on the #9. Thanks!
