### ISSUE TITLE
Errors: Error opening directory '/home/xxxx/Desktop': Too many open files + No characters showing

### ISSUE THREAD

**Issue by bsa2209** [spheras/desktopfolder#114]
### Description
After installation, I opened the app and this appeared:
![error](https://user-images.githubusercontent.com/43504282/45921440-09910d00-be8c-11e8-8d40-8fa522e0b54f.png)
When I copy and paste the "text" in a text editor I can see the message from the app:

Error opening directory '/home/xxxx/Desktop': Too many open files

This message appears even when Desktop Folder is the only app or file open.

I can click to exit this warning and the right-click in the desktop works, but it also doesn't show the proper characters.

### Steps to reproduce
1. Install app
2. Open app
3. Error

### Expected result
Working app.

### Actual result
Error.

### System Information
- OS: elementary OS 0.4.1 Loki (64-bit)
- Desktop Folder version: 1.0.6

### Terminal output
Not applicable.

**Comment by spheras** [comment]
Hi @bsa2209.  Strange issue.... :open_mouth:  What is the language you have in the OS?

**Comment by spheras** [comment]
closing it due to no answer after one month.  Please, reopen if interested.
