### ISSUE TITLE
Unable to move panel after dragging header behind Wingpanel

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#12]
If you drag a panel behind Wingpanel, you can't grab the header because it's behind Wingpanel. Resizing the panel vertically moves the header back below Wingpanel however.

This doesn't affect notes because they maximize when you drag them to the Wingpanel.

**Comment by spheras** [comment]
Wow! hehe, incredible, I've never test that :smile: 
I think the best option is:
- Allow moving panels from body (not only the header), this way you can get the panel from the body as well, and reposition it
- Give to the panels the same behaviour as the Notes, or at least, similar.

I'll give a try and submit a patch for this.

Thank you very much @aljelly

**Comment by spheras** [comment]
patch commited

**Comment by aljelly** [comment]
I think it might be better to do it similarly to how notes and other windows do it, instead of being able to grab all of the panel. Especially if selecting items by dragging a box will become a feature.

Since the panel can be maximized anyway by double clicking the header (which is actually interesting functionality as you can then use a maximized panel as a fake desktop), it could just stop going any further up if you drag it any further and maximize if you drop it on Wingpanel.

Alternatively you could allow placing items on the desktop without panels and then just disallow maximization of the panel.
