### ISSUE TITLE
Existing files on first startup are overlayed

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#125]
![workspace 1_085](https://user-images.githubusercontent.com/996240/47950934-ce393200-df51-11e8-8c22-4b8268d9f212.png)

Have multiple files on my desktop - on first startup all the icons are overlayed on top of each other.

Obviously easy enough if there is just a few files to space them manually - but I happen to have a folder with lots of files in it and all the hundreds of files are overlayed.

(Ubuntu Budgie 18.04 with budgie-desktop running v1.0.9 release)

**Comment by spheras** [comment]
mmm yes. I think it is easy to distribute them automatically the first time. The problem I see is that panels doesn't have scroll (and I'm not sure, but it seems very difficult to add an scroll there).

**Comment by fossfreedom** [comment]
How about initially never creating panels out of folders (.nopanel) on first startup?  Users I guess already expect to see folders on their desktop rather than a panel display.

Then somehow concentrate on distributing files & folders across the fake-desktop on first startup.

In a future enhancement would have to then resolve the scenario where a user drops hundreds of files into a "panel" folder - My thoughts here would be to initially don't worry about scrollbars - just distribute files & folders in a panel even if it exceeds the size of the panel.

If the user thinks the panel is now just a "bad idea" - maybe in a future enhancement add a right-click menu option to make a panel a "folder icon" - and likewise add a right-click menu option to a folder icon to make it a "panel"
