### ISSUE TITLE
Dynamically switch desktopfolder on/off

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#126]
With nautilus there is a dconf key that when poked will switch desktop-icons on or off.

I would like to investigate further if it is possible to have something similar for desktopfolder.

It may sound like a hack (it is) - but maybe on first startup of desktopfolder it spawns a separate daemon process that waits on a new key in com.github.spheras.desktopfolder.  If it is changed it will either kill the main desktopfolder process or spawn a desktopfolder process.

Thoughts? Is there a better way to implement this?

More than happy to throw a PR your way to resolve.

**Comment by spheras** [comment]
I don't understand this very well. If I'm not wrong the user will be the responsible to activate/deactivate desktopfolder. Why not just launch/kill desktopfolder process from that configuration window (and add/remove it from startup configuration)?

**Comment by spheras** [comment]
Ok, it seem a good option.
