### ISSUE TITLE
Photos and dragging issues

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#127]
on Ubuntu Budgie 18.04 v1.09 stable of desktopfolder

![workspace 1_086](https://user-images.githubusercontent.com/996240/47951211-7a304c80-df55-11e8-9229-fe9155f52fcc.png)

All photos are displayed with a black border as shown.

When clicking on the photo - the whole photo moves from top left to bottom right by a few pixels - I'm guessing around 15 to 30 pixels.  I can't drag the photo around the desktop.

There are no movement issues for panels, notes and files - so this is specific to photos.

Thoughts where in the code-base I should be looking at to investigate further?

**Comment by spheras** [comment]
Im not today at home, but I guess this is something of about transparency background of the photo window. You can see at the draw_background method of the PhotoWindow.vala how everything is rendered. The window background is not rendered to draw fixos and shadows over the image, but I dont know why its being rendered black in your case.

**Comment by fossfreedom** [comment]
Thanks for the hint - I will concentrate looking at that part of the code over the next week. cheers

**Comment by spheras** [comment]
@fossfreedom, it seems the problem is that the photo window hasn't a header -setheader(null)-  Not sure, but seems that in that case budgie-desktop put a window frame (with black opaque) over the photo.  I tried setting an empty header, and now it is shown correctly, but I need to confirm that it works also in elementary.  I will work on it.

**Comment by spheras** [comment]
@fossfreedom, yep it works. Do you mind to check it? thx!

**Comment by fossfreedom** [comment]
Works very nicely - well found! :)
