### ISSUE TITLE
update to Gtk+3.22, removing deprecated functions

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#128]
from #119,

update to Gtk+3.22. Investigate all the deprecated functions and alternatives

**Comment by spheras** [comment]
@fossfreedom, everything was updated to Gtk+3.22. It was very difficult on some points, but it seems now works even better (some bug fixes in the way)

**Comment by fossfreedom** [comment]
I've looked though the commits - superb cleanup and some very nice catches resolved in the code.

Major congrats!
