### ISSUE TITLE
Memory usage is approx 100Mb

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#130]
On startup, the memory usage is approx 100Mb for just a few files on the desktop.

Any ideas what the breakdown for that memory usage is?  i.e. what parts of the app is grabbing the greatest part of that 100Mb ?

**Comment by spheras** [comment]
I've been testing for a while and it is something around 30MB here (with some files, folders, and some empty panels)... In theory, nothing is being loaded memory but the settings of each panel/note/photo.  Look at your .desktopfolder .desktopnote and .desktopphoto, maybe the size is high.

**Comment by fossfreedom** [comment]
False alarm - yes agree with you - approx 30MB which is very similar to nautilus-desktop at the moment.

Sorry about raising this as a non-issue.
