### ISSUE TITLE
The reason for the "desktop folder" menu option?

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#134]
Really just a philosophical question really;

I noticed that there is a menu option to run DesktopFolder. Why?  There is an autostart to run desktopfolder and there doesnt appear to be any native GUI method to quit desktopfolder.  

Thus the design appears to be that desktopfolder is intended to run unattended - there doesnt appear to be a need for a /usr/share/applications/com.github.spheras.desktopfolder.desktop file.

Thoughts?

**Comment by spheras** [comment]
easy, because elementary appcenter tests fails if there isn't a menu option.

**Comment by fossfreedom** [comment]
Ah. Ok. Cheers for that. Would you mind if I patch that out as part of the Debian package?

**Comment by spheras** [comment]
sure, there is no need to have a menu entry option (apart from pass elementary os tests).
