### ISSUE TITLE
Cannot change icon for a .desktop copied from  /usr/share/applications

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#136]
*Feedback from the UB community - just recording this here so that the info is not forgotten*

v1.0.9 (master git)

"Drag and drop of the Calculator application in usr/share/applications to the desktop. I could rename it but there was no right-click “Change Icon” option."

Thoughts on where best to investigate further in the code-base?

**Comment by spheras** [comment]
I removed the condition to allow the change icon option. Now you can change the icon to everything... Not sure if it makes sense the change icon for a .desktop file, but.. well, why to forbid it.
