### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#139]
I was just looking at this https://github.com/spheras/desktopfolder/wiki/Translating

For most translators that would look a bit scary to-do.

Have you considered setting up a weblate or transifex project to support translations? - nice browser interface makes it easy to get translations.

If it helps - I can set up a subproject for our project (https://www.transifex.com/ubuntu-budgie)  and ping our existing 150+ translation team to help out with this project.  What I will do is upload all the current .po and .pot files.  Then when there are sufficient changes to the translations I could PR all of the updates for you to merge.

**Comment by fossfreedom** [comment]
Here you go: https://www.transifex.com/ubuntu-budgie/desktopfolder

**Comment by aljelly** [comment]
The translating page should probably be updated to instead link to that Transifex page if it's ready for people to use.

**Comment by aljelly** [comment]
I made the changes to the wiki page. The old instructions are still there as reference for anyone who wants to build the .pot file or otherwise translate manually. If the changes are sufficient (and you don't want to keep this issue open as a reminder) then you can close the issue.
