### ISSUE TITLE
Possible to drag icons on top of each other [link panel]

### ISSUE THREAD

**Issue by eljefuri** [spheras/desktopfolder#141]
I can drag icons on top of each other in the link panel, creating both a mess (leaving gaps), and also leaving no clear way to fix any of this. My assumption is that these should all [auto arrange](https://github.com/spheras/desktopfolder/issues/140) unless specified otherwise in some kind of preference.

**Comment by spheras** [comment]
Assuming we will have an auto arrange option:

- Not sure if auto arrange should be the default option, currently is not and that is a plus to dont make it the default.
- I don't understand what you propose exactly when the user drag an icon over/near another icon (when the autorrange is not activated in the future).  Could you add a small video or something to see exactly what you mean?

**Comment by eljefuri** [comment]
I strongly think that auto arrange should be default because when an new icon pops over the top of an old one, creating a stack, that feels like something is wrong, it feels like a bug.

Perhaps there is an issue of branding: You call this "Desktop Folder", which at least to me implies a restoration of standard desktop file/folder functionality found in most operating systems. But actually it is more _and less_ than that. In reality it is something like [DragThing](https://github.com/spheras/desktopfolder/issues/145) for Elementary more than it is a proper restoration of traditional desktop functionality.

I don't have a solution for what happens when the user drags an icon over/near another icon _when autoarrange is not active_. I think in that case, the icons simply overlap since the user is clearly directing it to be so. However, with autoarrange on (which implies grid layout being on too), I believe that things should simply work as described in [this](https://github.com/spheras/desktopfolder/issues/142) issue.

**Comment by spheras** [comment]
I will close this issue to describe the new feature into #148.
