### ISSUE TITLE
Icons should visually nudge each other out of the way when dragging [link panel]

### ISSUE THREAD

**Issue by eljefuri** [spheras/desktopfolder#142]
Although I support [automatically arranging](https://github.com/spheras/desktopfolder/issues/140) as a default action, the UX for manual arrangement in my opinion should behave [exactly like iOS does](https://youtu.be/FnG1GHVNVy4?t=23).

**Comment by spheras** [comment]
wow, beautiful... and difficult :smile:    Anyway, I think that's not manual arrangement, just the contrary, that's auto arrange... with manual arrangement I mean, no arrangement, the user put the icon whereever he/she considers.

**Comment by eljefuri** [comment]
Perhaps let's call it _manual arrangement on a grid_, or maybe _icon ordering on a grid_.

**Comment by spheras** [comment]
I will close this issue to describe the new feature into #148.
