### ISSUE TITLE
Add animation to make windows scoot out of the way on SUPER+D

### ISSUE THREAD

**Issue by eljefuri** [spheras/desktopfolder#147]
The present situation where all windows immediately disappear upon SUPER+D is maybe a bit frightening to a user who casually (or accidentally) tries it. I recommend gently but quickly sliding the windows out of the way, per macOS. [Here](https://youtu.be/WbgRLeMH6QM?t=67) is an example video of how that looks. [Here](https://youtu.be/UtbvTNDN3FE?t=72) is another.

**Comment by Jacob-Vlijm** [comment]
This has nothing to do with desktopfolder. It is a window manager thing. Options depend on what distro/windowmanager you are using.

**Comment by fossfreedom** [comment]
Just to clarify - what is this issue suggesting?  To toggle all application windows from visible to hide?

Or is referring to toggling desktop icons on/off.

Super+D is a bad choice for toggling desktop icons because it is a shortcut key for making applications hide/show on GNOME based desktop-environments.

If it is referring to windows toggling then I fail to see why the issue is applicable to DesktopFolder - that is a feature of the Window Manager - not something controlling the display of icons, panels, photos, notes etc on a desktop.

**Comment by eljefuri** [comment]
As I understand it, SUPER+D is _hiding the applications and showing the desktop_, plain and simple. If that is not what is going on here then I have *really* misunderstood things. :-)

**Comment by fossfreedom** [comment]
K. That should be a pantheon issue not desktopfolder imho. Similar to gnome shell/mutter and budgie/mutter that does applications toggle.

**Comment by eljefuri** [comment]
@spheras @fossfreedom I will close this for now until it is more clear and applicable.

**Comment by spheras** [comment]
Just to clarify. In elementary OS we don't have the SUPER+D shortcut to show the desktop. That's the reason why desktopfolder install the shortcut and provide an elemental implementation (calling wcnk library).  

In any case, the way (animation or whatever) those windows are minimized is something managed by the window manager of the system.

**Comment by Jacob-Vlijm** [comment]
Just to make sure, it isn't set by default, right? It would clash with our own Ubuntu Budgie shortcut, which call a script taking care of smooth show desktop functionality. This shortcut is set on first run after fresh install.

**Comment by spheras** [comment]
Hi @Jacob-Vlijm, yes, I asked @fossfreedom here ( #48) check that behavior. In theory, the application should detect conflicts and, in that case, now it doesn't install the shortcut.  Probably it works, but may be checked.  Anyway, as talked in #48, my concern is what to do in that case in the future. I mean, the idea was that in the the case to detect a conflict, we could ask to the user to put a different shortcut, but how to detect that the system has already the hide/show desktop shortcut?

**Comment by Jacob-Vlijm** [comment]
@spheras  In Budgie (!= Ubuntu Budgie) there is an applet, using Wnck similarly, no default Super + D like usually in Gnome-based distros.
**_However_** in Ubuntu Budgie, we added a script taking care of show desktop functionality: https://github.com/UbuntuBudgie/budgie-desktop-environment/blob/master/showdesktop/showdesktop. On first run, this script is set to run on Super + D. This is a one time thing, adding a trigger file in user's home directory to prevent repetitive procedure. On a dconf reset however, this shortcut is gone, and it would not be preferable if the shortcut was then taken by Desktop Folder's Wnck version. Personally, I don't think minimizing windows is a job that should be done by Desktop Folders, but requires a separate solution from the distro. It just makes things to complicated i.m.h.o.

**Comment by spheras** [comment]
@Jacob-Vlijm, I agree with you, it should be a distro solution to show desktop. In the case of elementary, there is no solution but calling toggle_showing_desktop manually (and installing the custom shortcut). So, the point is how to condition this custom shortcut installation by desktopfolder, currently it checks if the shortcut is registered already... Is this enough in the case of Budgie?

**Comment by Jacob-Vlijm** [comment]
@spheras In the meantime, @fossfreedom took a quick look in the code, it seems the showdesktop is only triggered in Pantheon, Which means it does not apply to Budgie I guess?

**Comment by spheras** [comment]
I'm not sure, but I think it apply to Budgie too. I took code from Pantheon to manage shortcuts, but it seems generic gnome  settings/code. You can see [here](https://github.com/spheras/desktopfolder/blob/master/src/utils/shortcut/CustomShortcutSettings.vala) how shortcuts are managed.  So, desktopfolder check if the custom shortcut exist already, if no, install it.  I will debug over budgie asap to see what is doing there exactly.
