### ISSUE TITLE
New Feature - Automatic Arrange

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#148]
This is a new Feature to be discussed and implemented. First I would like to find out the requirements for this new feature. There are some issues talking about this with different perspectives, these are #140, #141, #142, #76. I will close all these to start the discussion of the new feature here.  As always, the ideal will be to find the best balance between difficulty and usefulness.

**Comment by spheras** [comment]
I will start giving my opinion of this new feature.  Currently we have 3 different functionalities related to this:

- Totally manual arrange (this was the first made)
- Grid Positions (the icons are forced to be positioned in a grid, but wherever you want of the grid)
- Automatic Arrange for new Panels (icons recently created are positioned in the grid, but after that, you are free to move them wherever you want)

This is what we have, ordered historically.  For me, what this new feature means is a way to auto arrange icons over the panel, forbidding the manual drag-drop of them.   From this perspective, we will need some kind of sort (By name, by extension, ...), and what about the possibility to change the order to a custom order, where the user reposition one icon in a different place (like #148 describes [video](https://www.youtube.com/watch?v=FnG1GHVNVy4&feature=youtu.be&t=23)).

Therefore I see three different configurations:

- Totally Free (put whereever you want)
- Grid Alignment (put whereever you want, but following a grid)
- Automatic Arrange (icons are automatically arranged, and maybe you could reposition them manually)

I feel like 2 and 3 are very similar, and not sure if they should be the same.

One discussion will be, what should be the default option? Totally Free is currently the default, and that's a plus to be the default in the future, but.. well we need to discuss.

Hope this is useful to a start point of discussion.

**Comment by jica** [comment]
I think there are 2 configurations:
- Totally Free (put whereever you want)
- Grid Alignment (put whereever you want, but following a grid)
Also, we can add a new feature: **"order icons"** that will arrange icons automatically. But this is an action, not a arrangement configuration.

I think this is like windows 95/98 behaviour.

**Comment by aljelly** [comment]
I think that even with a "manual arrangement"/"totally free arrangement" mode, when you add a new item to the desktop it shouldn't overlap with other ones but try to put the new icon somewhere where there's free space. Once it's there though you'd be able to move it wherever you want, even over other icons (though I'm not sure why someone would want to do that). The current behaviour is a bit weird.

**Comment by spheras** [comment]
Ok, I'll take this feature, I think it is one of the most important issues now. My idea is:

- Put a scroll inside the panels, in a way that you are not restricted to the size of the panel to add more items inside.
- Allow 3 types of arragement:
  · Totally free, this is the basic feature we have.  If a new item is added, it will find the best place to not overlap.
  · Free, but following a grid. I'll try to improve the visual grid. Need to be improved also when you drag an icon to a position where there exists a different icon. (how could I add visual animations to improve the user experience?).  If a new item is added, it will find the best/next gap inside the grid.
  · Automatic, totally new. The system will organize the items for you. 
- When the panel is resized, unless in the free mode, icons will try to find the best position.
- Add order actions to order the icons in different ways (by name, size, extension, ... others?) The order will affect to all the modes. i.e. in the free mode, the algorithm will sort the icons but they will continue free after that.

The default configuration for new panels will be ...? not sure yet.. but users could change that default behavior by generic configuration.

**Comment by spheras** [comment]
I started in a new branch this feature. You can see here how is going the new grid arrangement
![testing-grid](https://user-images.githubusercontent.com/3862933/48655216-7c45e100-ea14-11e8-907c-4370e9c21a82.gif)

**Comment by aljelly** [comment]
I think Link Panels specifically should use managed by default so that you can resize the panel and it will automatically arrange the icons. Either that or try and automatically wrap icons on grid mode without changing the order of icons (and respect when there are gaps in the grid) when you resize a panel.

It's just otherwise this looks a bit weird and feels unexpected:

![image](https://user-images.githubusercontent.com/10395308/48839838-aedd3a00-ed84-11e8-95b4-c7fcad049010.png)

**Comment by spheras** [comment]
I have a pending issue regarding automatically arrange: a global setting to define what is your arrange preference by default when creating panels.  The point is when such preference is available, will feel strange to have different hardcoded default only for links panel, don't you think?

**Comment by spheras** [comment]
I will probably merge (if everything is OK) the branch "feature-automaticarrange" during this weekend. The functionality is practically done, the only pending issue is trying to force no overlapping icons when you move an icon in the Grid arrangement (I'm thinking the possibility to create panels when you overlap icons, similar to android/ios).

Please, the branch is an important change, please, review when possible.

**Comment by Jacob-Vlijm** [comment]
WOW, testing the looks like great work!! I LOVE the option to switch off/on the icons by gsettings. Options to arrange seem fine to me.
A few things that occur to me: 
- The size of the grid cells seems to be a bit tiny:
 
  ![afbeelding](https://user-images.githubusercontent.com/8932980/48915848-76bb2180-ee80-11e8-9e79-aa0b1f87b36f.png)

- The animation shows quite different here, more like a crosshair, padding between cells is gone:

    
    ![afbeelding](https://user-images.githubusercontent.com/8932980/48915914-b4b84580-ee80-11e8-9bc5-6eda33b4c5f1.png)

**Comment by fossfreedom** [comment]
![workspace 1_090](https://user-images.githubusercontent.com/996240/48919543-42992e00-ee8b-11e8-8739-1861f29ad5e3.png)

I right clicked approx under the untitled folder icon to create a new panel.  As you can see the panel is created quite away from where you right clicked from.  Oddly as you can see in the terminal it reports a negative gint value.

**Comment by aljelly** [comment]
> * The size of the grid cells seems to be a bit tiny:

It could be both a different font that turns out to be slightly bigger (Ubuntu on Ubuntu Budgie instead of Open Sans which elementary uses) combined with the fact that it's bold. Perhaps the gaps between the icons could be increased. For reference, Files on elementary has a larger gap between icons even when the size is decreased to Desktop Folder's icon size:

![image](https://user-images.githubusercontent.com/10395308/48922612-de349980-ee9f-11e8-9c13-a5361ae20b45.png)

Maybe that size gap would be a bit too much for Desktop Folder though.

> Issue 1:
> 
> ![workspace 1_090](https://user-images.githubusercontent.com/996240/48919543-42992e00-ee8b-11e8-8739-1861f29ad5e3.png)
> 
> I right clicked approx under the untitled folder icon to create a new panel. As you can see the panel is created quite away from where you right clicked from. Oddly as you can see in the terminal it reports a negative gint value.

Yep, there's an issue for that at #175. The current code is positioning the new panel where the cursor is when you click on the context menu "Panel" option, instead of where you initially right clicked.

> Issue 2:
> 
> I then within the panel right clicked and created a new empty file and got this error message:
> 
> ![workspace 1_091](https://user-images.githubusercontent.com/996240/48919633-d66afa00-ee8b-11e8-9072-e4e8f69aafe9.png)

I've got this once or twice. I recently modified the creating new file code, I think I recognise the message and I might've accidentally made a bug there. I believe it's the part of the code where it searches each icon to try to match the name to find the icon it needs. I don't quite remember and it's probably messy, but I think it was because I couldn't find anything to simply access the index with a `icon[icon_index]` like thing.

If you run `G_MESSAGES_DEBUG=all com.github.spheras.desktopfolder` and try to replicate the error again the debug messages might give an idea what's going on.

**Comment by Jacob-Vlijm** [comment]
Ideally, the size of the cells could be set in gsettings, so distro's can set an override.

**Comment by fossfreedom** [comment]
@aljelly   trace at the point of creating the empty file:

```
(com.github.spheras.desktopfolder:4301): GLib-DEBUG: 22:38:23.412: posix_spawn avoided (automatic reaping requested) (fd close requested) 
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.494: watch_fast: "/com/github/spheras/desktopfolder/" (establishing: 0, active: 1)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.495: unwatch_fast: "/com/github/spheras/desktopfolder/" (active: 2, establishing: 0)
** (com.github.spheras.desktopfolder:4301): DEBUG: 22:38:23.496: FolderManager.vala:208: Monitoring: /home/dad/Desktop/Untitled Panel 2
Error: Couldn't find the newly created folder's item.(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.558: watch_fast: "/com/github/spheras/desktopfolder/" (establishing: 0, active: 1)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.558: unwatch_fast: "/com/github/spheras/desktopfolder/" (active: 2, establishing: 0)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.577: watch_fast: "/com/github/spheras/desktopfolder/" (establishing: 0, active: 1)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.577: unwatch_fast: "/com/github/spheras/desktopfolder/" (active: 2, establishing: 0)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.580: watch_fast: "/com/github/spheras/desktopfolder/" (establishing: 0, active: 1)
(com.github.spheras.desktopfolder:4301): dconf-DEBUG: 22:38:23.581: unwatch_fast: "/com/github/spheras/desktopfolder/" (active: 2, establishing: 0)

```

**Comment by aljelly** [comment]
@fossfreedom Both the issues you mentioned should be fixed/added. The second issue might not be totally fixed however, I got the same error again at one point but I haven't been able to reproduce it.

**Comment by spheras** [comment]
@Jacob-Vlijm, that screenshot is strange. I will check the problem directly on budgie because your labels widths are wrong and even the position on the cells of each icon.

Regarding animation, I have been touching here and there to get the "best animation"... I had different versions, that's the current one... The idea was to clear the position where you will put the icon to see clearly the background there, on the other version the problem was that it was practically white, and was something unclear... But, I'm not sure what's better or ... beautiful... I'm just experimenting with animations in gtk (by the way, Can you advise me a library or something to perform animations in gtk?)

**Comment by spheras** [comment]
@Jacob-Vlijm The problem regarding icons size was the gtk.entry default style in budgie (compared to elementary). I modified the application styles to force the width of the gtk.entry in the application and now seems to take a correct with. Anyway, the entry is still ugly when you modify the name of a file, the height needs to be polished a bit (margin, paddings, I will work on it). You can check now if the problem is solved.  Regarding the size of the cells, that's true, there is an issue about the size of icons, I think we could in the future try to set it configurable, and even the separation between icons.

**Comment by Jacob-Vlijm** [comment]
@spheras Thanks again, just tested after commit 4984392, The overlapping text is gone, but it still looks like a Saturday afternoon in the centre of Amsterdam :) 

![afbeelding](https://user-images.githubusercontent.com/8932980/48954978-07126880-ef4c-11e8-9aab-c5022dcc4c4d.png)

I love the double-click-hide icons feature!

**Comment by spheras** [comment]
Regarding drag, the problem for other arrangements methods is that when dragging, you are moving the icon. For now the solution is press ctrl key before start dragging... I think in the future we could implement something more sophisticated, something like: if you drag the icon outside the panel, then you will restore de original icon position and start a drag/drop file instead.

**Comment by Jacob-Vlijm** [comment]
Other issues I am experiencing on "Let application decide":

- desktopfolders seems to have lost the correct location(s) of its items. Clicking on an empty space acts like I right-click an item:

    ![afbeelding](https://user-images.githubusercontent.com/8932980/48955322-a08e4a00-ef4d-11e8-9e8d-da828cdb4cba.png)

- In the same stuation: double clicking on some folders on the desktop works fine (they open), other move a few px to the right, clicking again makes them move even further to the right.

**Comment by Jacob-Vlijm** [comment]
Another one on Let app decide:
- It seems the full desktop size is used, not the working area, including the strut-values, as defined by possible panels and launchers. It can possibly lead to conflicting situations: 

    
![afbeelding](https://user-images.githubusercontent.com/8932980/48955929-8ace5400-ef50-11e8-8702-b78d8083a835.png)

**Comment by spheras** [comment]
> Other issues I am experiencing on "Let application decide":
> 
> * desktopfolders seems to have lost the correct location(s) of its items. Clicking on an empty space acts like I right-click an item:
>   ![afbeelding](https://user-images.githubusercontent.com/8932980/48955322-a08e4a00-ef4d-11e8-9e8d-da828cdb4cba.png)
> * In the same stuation: double clicking on some folders on the desktop works fine (they open), other move a few px to the right, clicking again makes them move even further to the right.

@Jacob-Vlijm, I can't reproduce in budgie or elementary those issues... could you specify exactly what I must do to reproduce the problem?

**Comment by Jacob-Vlijm** [comment]
@spheras 
1. Switch to "let app decide"
2. start dragging desktop items to the top left. Here we see there might be a flaw in the algorithm to decide on placement, since the layout becomes a beat unexpected / strange.
3. Once there is a blank space created this way:

![afbeelding](https://user-images.githubusercontent.com/8932980/48957257-c882ab00-ef57-11e8-8980-d96e4e354f1d.png)

.. we can see clicking in the blank space incorrectly assumes a desktop item (I clicked on the desktop in the top/teft)

![afbeelding](https://user-images.githubusercontent.com/8932980/48957302-05e73880-ef58-11e8-943a-2f851304843a.png)

We can also see the icons are placed behind Plank.

**Comment by Jacob-Vlijm** [comment]
BTW, I just noticed it creates lots of links in my Desktop folder, right?

**Comment by spheras** [comment]
@Jacob-Vlijm,

sorry, I can't reproduce. I don't understand how your icons aren't at the top left when you set the "let app decide" configuration.  This is a capture with UB. What I'm doing wrong?

![ezgif-4-66ef27adf28c](https://user-images.githubusercontent.com/3862933/48959124-b6a70500-ef63-11e8-9354-6d2847b6cc5e.gif)

**Comment by Jacob-Vlijm** [comment]
@spheras if you pick "let app decide", you are still able to drag. Let me make a screencast... need to compile feature version first, a minute..

**Comment by Jacob-Vlijm** [comment]
@spheras ^

**Comment by spheras** [comment]
:open_mouth: I don't whats happening there, but it seems you have transparent icons!! what are those icons?? (could you mv your current ~/desktop and check with normal icons?)

**Comment by Jacob-Vlijm** [comment]
@spheras Haha, no, they have nothing to do with the issue, I simply wanted to know what icon spheras showed if no `Icon=` line is set in a .desktop file. nautilus shows a generic icon, desktopfolders none, which is something we might have to look into later. To set the `Icon=` line is not  a must normally. It does not change anything to what happens though. You'd like to see the proof?

**Comment by Jacob-Vlijm** [comment]
After the previous episode, the whole organize machine seems to stop working btw. No settng has any effect, desktop looks like a mess :) 
restarting desktop folders....

**Comment by spheras** [comment]
Ok, repetitive links is a bug/feature (:D) introduced in the branch, but easy to solve. The "empty" space was occupied by an icon, a transparent icon, I think that's easy to deduce: no way to launch the icon popup without an icon, and you can see how the items are going to the right each time you add a "transparent" icon (the arrangement place all the icons ordered).  The point is, how the hell are those "transparent" icons created. Not sure if those transparent icons at the beginning of the row are the same or related with the "no Icon= line" .desktop files you mention.

**Comment by Jacob-Vlijm** [comment]
@spheras they are apparently not, I removed those. For me personally, I'd prefer the grid/free arrangements. To solve the geometry stuff is really complicated, especially on multimonitor situations and panels/ plank on left right, and the "let app decide" will forcefully use those conflicting areas.

**Comment by spheras** [comment]
@Jacob-Vlijm, I've pushed a default padding of 10 px between items. Moreover, you can now modify this default padding for new panels and change the padding for each panel. Check it if possible and give me your opinion.

**Comment by Jacob-Vlijm** [comment]
@spheras +1 (and more!) This is awesome!!

**Comment by aljelly** [comment]
I was trying to make the app act like elementary's Files app where if you drag a file into the same directory, it creates a link. I think the problem might be that I should've changed the default drag & drop option to link when you try to drag the file into the same directory.

I'm not sure what's going on regarding the creating lots of files thing, isn't it working if you're dragging and dropping files loads of times? If you've selected "Let app manage" and drag & drop a file into the same directory/panel, that was the intention. Maybe the cursor should be updated to show the link icon instead of the move icon though.

**Comment by spheras** [comment]
@aljelly, Ok, I've noticed this behaviour in Files the first time just now :rofl:  Do you know if this is something special from elementary only or a common behaviour for others file managers?  Not sure (as a user) if this will come into a hell of links, or it is just because we have been testing a lot moving items.  What do you think?
I agree, in case we leave that behaviour, the action icon should be the link.

**Comment by aljelly** [comment]
Both in Files and how it worked here pressing Esc cancelled the drag & drop (probably universal GTK drag & drop thing). I used it in Files a lot to create links until Juno was released. In Juno there's a "Copy as Link" option which makes a link when you paste, so instead I can just select Copy as Link, go to the directory I want the link in and paste.

**Comment by spheras** [comment]
I've been working on this for the grid
![animations](https://user-images.githubusercontent.com/3862933/49245744-894ed100-f413-11e8-9c0d-9910626cc71d.gif)

Hope you enjoy!

**Comment by fossfreedom** [comment]
Just a bit of a FYI ... gnome shell guys have released their first release candidate extension... obviously cannot be used on any other DE ... but make what you will. Very much work in progress 

https://www.youtube.com/watch?v=-T_Kj2116zc

**Comment by spheras** [comment]
The branch was merged. I'm closing this issue.
