### ISSUE TITLE
Does not work with elementaryOS Juno (in a VM)

### ISSUE THREAD

**Issue by Jeansen** [spheras/desktopfolder#149]
I've done a fresh install of Juno in a VM. I used appcenter for installing desktopfolder. Installation worked fine. But when I call the app ... nothing happens. If I call it from the command line ... nothing happens.

If I check /var/log/syslog I can see the following whenever I call the app.

```
Nov 12 21:53:18 marcel-VirtualBox gala.desktop[1252]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2600003 ()
```

**Comment by spheras** [comment]
Have you tried doing a right click over the desktop? One of the last changes was to not to open a panel by default, maybe it seems that nothing happens

**Comment by Jeansen** [comment]
Yes, I have. But I only get the general settings for wallpapers etc. And like I wrote, if I run the application it directly quits again.

**Comment by spheras** [comment]
Sorry, maybe I didn't understand the problem described. For the symptoms you describe, everything seems to work correctly. I will try to explain better:

-  When you try to run desktopfolder it checks if there is an instance running already, if that happens, it quit directly, as you describe. Desktopfolder is configured to run on the startup, you don't need to run it manually. You can check if the process is running `ps -A | grep com.github.sph`
- If you do right click over the desktop (without desktopfolder running) nothing happens. Elementary doesn't have a menu or something like that when you right click it.  So, that popup is from Desktopfolder. 
- In the popup, you can change the wallpaper, but you can also create panels, and so. I will attach a picture of that menu (in spanish but similar)

![popup](https://user-images.githubusercontent.com/3862933/48396058-79e43e00-e719-11e8-9e51-42fb3ba6e9c2.png)

As I said, maybe I missed something from your explanation, let me know.

**Comment by Jeansen** [comment]
Ah.... I see now. Did not get it with the panel. Now it seems to work. I am sorry, my bad. But thank you so much for your patience and explanation.
