### ISSUE TITLE
Only show new Panel/Note/Photo options in the panel context menu when desktop is disabled

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#159]
Now that you can right click the desktop, perhaps the new Panel/Link Panel/Note/Photo options shouldn't show in a panel's right click menu unless icons on the desktop have been disabled (because the context menu of desktop windows would then be the only way to create new windows). For notes/photos the New option wouldn't show at all (unless desktop is disabled) because those four options are the only options in the menu.

It's not an extremely important change though and it's probably just a simple if condition in the code.

Screenshot to illustrate what I'm talking about:

![image](https://user-images.githubusercontent.com/10395308/48666182-99ca8780-eab4-11e8-8961-0dec02121b4b.png)

The four items at the bottom wouldn't show unless you can't right click the desktop (i.e. when icons on the desktop are disabled).

**Comment by eljefuri** [comment]
Great idea. By the way it's super touching to see how people seem to really care about this application. Clearly everyone wants it to be as useful as possible, including the very responsive and thoughtful @spheras 

So thanks everyone!
