### ISSUE TITLE
Objections to use a sytem call here?

### ISSUE THREAD

**Issue by Jacob-Vlijm** [spheras/desktopfolder#174]
Hi Jose, We are working on a pr, adding a "Show Properties" to the right-click menu, like:

![afbeelding](https://user-images.githubusercontent.com/8932980/48845579-2a4ae580-ed9d-11e8-9efa-5ceb39876f77.png)
This info would, in case of a directory, include the number of files in it. In Vala, it turns out to be quite a hassle to retrieve that info, and would lead to "too much honor" in the sense of additional code for such a simple thing.
The question is: would you have any negative feelings on using a simple `find` system call here? Less then a full line, and doing the job perfectly.

**Comment by spheras** [comment]
mmm I guess it is right, it is a generic command, isn't it? Probably you are much more experienced than me in Gtk :smile: If you think it is the best way, it is perfect for me too.

**Comment by Jacob-Vlijm** [comment]
Thanks a lot!
