### ISSUE TITLE
Position window where you first right click for the context menu

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#175]
Currently when you right click, go to "New" and create a panel/note, it will be positioned where the mouse is when you click on Panel/Note in the context menu. This is a bit strange. Instead it should be positioned where you initially right clicked to show the context menu.

**Comment by spheras** [comment]
mmm Yes, I agree when the right menu is over the desktop panel... but it is different if you right click over a panel. That should be taken into consideration. In the first case we should save the point where it was showed the menu.. :+1:
