### ISSUE TITLE
Allow desktop to be toggled on and off without relogging

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#177]
Will also allow right clicking on the desktop even when desktop is disabled.

**Comment by spheras** [comment]
@aljelly, I've seen the changes, they are fine. I understand this issue and is obviously a good issue. But, I've seen that the PR you did you now are not hiding/removing the desktop panel (only hiding icons). That's what I don't understand. Really make it sense? I'm thinking out loud, I'm not sure if it is right or not.  I'm wondering myself if someone who doesn't want icons over the desktop will want to have a transparent panel over the desktop... One of the concerns we had at the beginning (before we had a desktop panel) was that the "big desktop panel" could conflict with the interaction with others applets/gadgets you had in the desktop, and that could be a reason to avoid putting a panel there...  So, we decided to have a configurable Transparent Desktop Panel.

what is your opinion about all this?? I have a lot of doubts.

**Comment by aljelly** [comment]
The idea behind leaving the desktop panel there was so you can right click it and create panels as you would with the icons enabled. Right clicking on already present windows to create new windows feels strange if all you wanted is the desktop icons gone, it makes sense to still be able to right click the desktop to do things like create panels in that case.

Ideally the desktop panel would stay behind all apps as much as possible so there would be no ordering problems. I don't know how much the code tries to prevent something getting behind it. I just tried one or two apps on AppCenter that stay behind on the desktop (Nimbus, Principles) and neither of them seem to compete with Desktop Folder for ordering even when launching them before and after Desktop Folder. Not sure if there would be any other apps that would try to order itself as far back as possible apart from other Desktop Folder-like apps (the user probably shouldn't be running two desktop-providing apps at the same time).

Perhaps if any issues or complaints that "a window from another app is behind the desktop and I can't do anything with it" come up we could add a general "Disable desktop" option that would completely remove the desktop window on next login (in other words what the previous behaviour did). Or if you want I could add it to the current PR.

**Comment by aljelly** [comment]
I've added disabling DesktopWindow back but commented it out so it's easy to just uncomment the comment block in PanelProperties and it's back. Still requires logging out and in though because it my attempts to make it happen without requiring that were causing Gala to crash.
