### ISSUE TITLE
Don't show version at properties page

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#178]
Mostly because the version can be found when you go to AppCenter and find Desktop Folder in the list on the Installed tab. And for the purposes of troubleshooting people could be asked to either check there or run `com.github.spheras.desktopfolder --version` to find the version.

**Comment by spheras** [comment]
Regarding AppCenter, no everybody uses this application in Elementary (and not sure, but there you see the last version, no what you have installed). I agree with the second part, the only problem I see is that not everybody knows how to use the console (I know it is difficult to find in Linux but that's what Linux community is looking for, to be more... accessible - in fact that was the main reason why I created desktopfolder, to attract people, friends, that were scared in a desktop without icons...).  To be honest, I don't think that small info at the bottom of the configuration panel is a problem, and could help us to solve issues. Do you mind if we let it there?

**Comment by aljelly** [comment]
Okay, we'll leave it.
