### ISSUE TITLE
[feature-automaticarrange] Icons are initially very slightly off grid

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#180]
Steps to reproduce:

- Set a panel or the desktop to "Grid"
- Select "Reorganize Icons" (or "Force Reorganization") on it
- Close and relaunch Desktop Folder
- Select "Reorganize Icons" (or "Force Reorganization") on that panel/the desktop again

The icons will slightly move because they're initially slightly off grid.

**Comment by aljelly** [comment]
This is back as of the recent configurable spacing additions

**Comment by spheras** [comment]
mmm I can't reproduce... Maybe there is a different step to reproduce?

**Comment by aljelly** [comment]
Basically it seemed that the padding wasn't being applied to the very left of the icons initially. So when I selected "Reorganise Icons" they all shifted to the right. This was on the desktop, not sure if it was happening in panels as well, and I think it was in grid mode.

**Comment by spheras** [comment]
Ok, it seems the problem now is a bit different as the described initially. Now the problem appears between the "let app manage" and "grid". Effectively, "let app manage" config doesn't have the initial left margin. I will fix.

**Comment by spheras** [comment]
seem correct now, check it, please.
