### ISSUE TITLE
Window manager crash on first time creating a link to a file

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#182]
Using the featured branch & budgie-desktop

Steps to repeat:

start com.github.spheras.desktopfolder from a terminal. i.e. must be the first time to run.
Create a panel
Within that panel try to create a link to a file.

The window manager crashes. Then the dialog appears

Next time you try to create a link to a file, the dialog asking for the path appears correctly without the window manager crashing.

EDIT: Same thing happens with "Link to folder" -

**Comment by aljelly** [comment]
I was able to get window manager crashes caused by Desktop Folder when attempting to make the entire desktop toggleable without logging out and in again (it was at least happening with the properties panel, didn't try the select file dialogs).

- Can you run `journalctl`, press <kbd>End</kbd> and see what the window manager says when it crashes?
- Is Budgie's window manager based on Mutter (like elementary's Gala window manager)?
- Try creating a new panel and clicking the gear icon to show the properties panel. Does it also cause the window manager crash?
- Does it only happen on the feature branch? If that's the case, I might be able to find out at what point the crashing started happening.

This is `journalctl`'s output for me when I was getting the WM crashes:

```
Nov 22 02:01:54 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:55 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:56 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:56 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:56 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:56 aled-eOS gala.desktop[30271]: Window manager warning: Attempt to perform window operation 1 on window 0x2200044 (hgcjfjt) when operation 1 on 0x2200044 (hgcjfjt) already in effect
Nov 22 02:01:58 aled-eOS gala[30271]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 22 02:01:58 aled-eOS gala.desktop[30271]: Window manager warning: Attempt to perform window operation 1 on window 0x2200044 (hgcjfjt) when operation 1 on 0x2200044 (hgcjfjt) already in effect
Nov 22 02:01:58 aled-eOS gala.desktop[30271]: **
Nov 22 02:01:58 aled-eOS gala.desktop[30271]: mutter:ERROR:x11/group.c:71:meta_group_new: assertion failed: (g_hash_table_lookup (display->groups_by_leader, &group_leader) == NULL)
Nov 22 02:01:58 aled-eOS gnome-session[1222]: gnome-session-binary[1222]: WARNING: Application 'gala.desktop' killed by signal 6
Nov 22 02:01:58 aled-eOS gnome-session-binary[1222]: WARNING: Application 'gala.desktop' killed by signal 6
Nov 22 02:02:00 aled-eOS gala.desktop[25953]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2200003 specified for 0x2200036 (Apps).
Nov 22 02:02:00 aled-eOS gala.desktop[25953]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2200003 specified for 0x2200044 (hgcjfjt).
```

The stand out line being:

```
Nov 22 02:01:58 aled-eOS gala.desktop[30271]: mutter:ERROR:x11/group.c:71:meta_group_new: assertion failed: (g_hash_table_lookup (display->groups_by_leader, &group_leader) == NULL)
```

**Comment by spheras** [comment]
@fossfreedom, I can't reproduce. Perhaps was the problem solved in the last version by chance? Could you check if you still have the problem (I'm testing with the feature-automaticarrange branch)

![ezgif-4-bbe3d44059c5](https://user-images.githubusercontent.com/3862933/48959282-9c215b80-ef64-11e8-8a7b-d2b27ed3f4e9.gif)

**Comment by fossfreedom** [comment]
I can - I'll try to dig deeper.  Will get back to you

On Fri, 23 Nov 2018 at 20:14, José Amuedo Salmerón <notifications@github.com<mailto:notifications@github.com>> wrote:

@fossfreedom<https://github.com/fossfreedom>, I can't reproduce. Perhaps was the problem solved in the last version by chance? Could you check if you still have the problem (I'm testing with the feature-automaticarrange branch)

[ezgif-4-bbe3d44059c5]<https://user-images.githubusercontent.com/3862933/48959282-9c215b80-ef64-11e8-8a7b-d2b27ed3f4e9.gif>

**Comment by fossfreedom** [comment]
huh?  After logging out and logging in all is fixed.

I'll keep an eye on this - but lets close for now.
