### ISSUE TITLE
Panel labels sometimes start renaming when Desktop Folder is launched

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#184]
Guess: probably the `edit_label_on_creation` setting for panels is not always being set to `false` after the initial renaming.

At the very least we should probably make sure it's set to `false` for all Panels/Notes on startup while trying to make sure it works better generally.

**Comment by spheras** [comment]
Is this still happening? I haven't seen this problem lately, maybe it is fixed (accidentally :laughing:  )

**Comment by spheras** [comment]
@aljelly, I think this is not happening any more, don't know why, but it seems fixed. Please, reopen if you see this happening again.
