### ISSUE TITLE
Drag and drop folders from Files to panels

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#20]
Currently you can't drag and drop a folder to a Panel, only files are working.

**Comment by Philip-Scott** [comment]
Maybe things in panels should only be Links, and none be actual "folders" for "files"?

**Comment by spheras** [comment]
well, that's a big filosophical change for the app :smile:. In my opinion you must have both options, links and real files. Panels are the representation of a phisical folder in your Desktop folder (the names comes from here).  Honestly, I think, this way the tool is more powerful.

I have doubts about the drag and drop. Perphaps, the drag and drop should only drop links? Not sure. I've just uploaded a commit to allow drag and drop folders, but it need to be improved with a cancellable gtk window (progress), or ... maybe.. if you drag a folder, just link to the folder...

**Comment by aljelly** [comment]
This is how drag & drop behaves in Windows (both for another folder in Explorer and the desktop):

 - Dragging & dropping something from once place to another with no modifier keys held down moves the file to the new location.
 - Dragging & dropping while holding CTRL creates a copy of the file.
 - Dragging & dropping while holding ALT creates a link/shortcut.

I think it'd be best to do the same thing as drag & drop would do to another folder, except with elementary OS's behaviour. That way the behaviour is consistent with the rest of elementary OS.

**Comment by spheras** [comment]
I like that behaviour. I will experiment with that, it seems easy. What I would like, and I don't know exactly how to do, is to let it know to the user someway... I'm refering to the text shown below the icon dragged ("Copy to","Move to","Link to"). Perhaps I could show a message at the bottom of the panel, indicating the action that will be produced.

**Comment by aljelly** [comment]
I was going to say "_might be better to leave the functionality for now as elementary OS doesn't do this yet_" but I think it's quite useful for this situation.

Maybe show an indicator (i.e. a small box with text and an icon) by the mouse similar to how Windows does it. It could then be replaced if/when elementary OS gets this functionality. Not sure how easy it would be to do that.

**Comment by spheras** [comment]
I just uploaded a commit solving this functionality. I tried to adjust the Files behaviour, so, by default, you move files/folders, with control pressed, you copy, and I added shift or alt to link files (in fact it seems that finally Files support the Link Drag Action)

It is nice to see it in action

![dragndrop-testing](https://user-images.githubusercontent.com/3862933/31843081-6b270b18-b5f1-11e7-9794-571f444c4b9d.gif)

**Comment by spheras** [comment]
On the other side, I didn't mention that you can now copy/move/link folders as well. Moreover, whenever you are copying something there appears a progressdialog very similar to the Files progress dialog (most of the window is copied from Files)

**Comment by aljelly** [comment]
That looks good!
