### ISSUE TITLE
Unable to Delete Panel

### ISSUE THREAD

**Issue by rainer2208** [spheras/desktopfolder#209]
I am unable to delete the panel. When I try to, I am getting the error message "Unable to create trashing file for /home/user/Desktop/My Panel. Permission denied".

**Comment by spheras** [comment]
Hello @rainer2208. The error sounds like your user doesn't have permission on the trash folder?? Is that right?? Have you tried removing files from a different file manager? What OS are you running?

Here a similar problem: https://www.linuxquestions.org/questions/showthread.php?s=453e2b69389f6ac052064d7f3307bc13&p=5653243#post5653243

**Comment by rainer2208** [comment]
Hi @spheras  ... you were absolutely correct. I somehow  changed the ownership of my trash bin. Changing it back with "sudo chown -R "$USER" ~/.local/share/Trash" solved the problem. Kindly discard the issue ... Sorry about the extra work.

**Comment by spheras** [comment]
Ok, no worries. Thanks!
