### ISSUE TITLE
Rename of a file via Files moves the icon to the first line

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#212]
Reported by the UB community

Desktop is using the "Free" arrangement (i.e. not grid or app arrange)

move any icon to any position on the desktop.

Open Files (Nautilus) and rename that ~/Desktop/filename

Unexpectedly the icon moved its position on the desktop to the first "line" on the desktop.  It should have stayed where it was positioned.

**Comment by spheras** [comment]
fixed
