### ISSUE TITLE
Drag and drop of Snap apps to the desktop does not work

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#218]
Just a quick issue to record an observation on the budgie-desktop.  I suspect it will apply to elementary.

From the start menu you can drag and drop an application onto the desktop.  Double clicking that icon on the desktop launches the application.

From the start menu you cannot drag and drop a Snap application onto the desktop.  Possibly flatpak's have the same issue?

If I copy the snap .desktop file via the command-line onto the desktop then that works just fine.

e.g. 

`cp /var/lib/snapd/desktop/applications/ubuntu-budgie-welcome_budgie-welcome.desktop ~/Desktop/`

**Comment by fossfreedom** [comment]
More info here:

![image](https://user-images.githubusercontent.com/996240/49528073-234ac980-f8ab-11e8-8461-fac64b4c7a0e.png)

budgie-desktop and gnome-shell have the concept of allowing distro maintainers to override the package managers .desktop file in /usr/share/applications

So in budgie-desktop case you can place a .desktop file in /usr/share/budgie-desktop/applications and the menu will display the details of that .desktop file - not the contents in /usr/share/applications.

This is the same concept that a user has if they override the package by placing a .desktop file in ~/.local/share/applications

When dragging and dropping from the menu to the desktop, DesktopFolder treats this as a move request - hence you see in the terminal "permission denied".

I repeated this for a snap application and it also had a "permission denied" message.

Possibly the drag and drop code should allow all .desktop files in a "system" location (i.e. not from the home folder) to be treated as a copy event - not a move event.

**Comment by spheras** [comment]
please, check it, I think it is fixed now.
