### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Vladimir-csp** [spheras/desktopfolder#222]
I suppose global options like state of main Desktop directory panel is storable, but  I do not see a config file or config dir in `$XDG_CONFIG_HOME` or  even `$HOME`. Is XDG directory spec supported?

**Comment by fossfreedom** [comment]
This is part of https://github.com/spheras/desktopfolder/pull/216 where I'm going to be using xdg-user-dirs to remember/use the value held.

**Comment by Vladimir-csp** [comment]
No, I'm talking about config file for desktopfolder itself and its override mechanism in accordance to XDG_CONFIG_DIRS, XDG_CONFIG_HOME heirarcy.

**Comment by aljelly** [comment]
All of Desktop Folder's settings are set in gschema keys while the .desktopfolder files are the specific settings for the folder that contains the file.

To configure Desktop Folder itself use `gsettings` or `dconf`, and look in `com.github.spheras.desktopfolder` (e.g. `gsettings list-keys com.github.spheras.desktopfolder`) though currently IIRC all of Desktop Folder's settings are settable from within the application.

**Comment by Vladimir-csp** [comment]
Oh, that's unfortunate. I was looking for something more independent from DE overengineering and dconf in particular. Any chance of normal XDG-compliant config files in the future?

**Comment by spheras** [comment]
@Vladimir-csp, I'm afraid this will not change in the near future because it is in the core of the application. Anyway, it sounds interesting to think about, who knows. I'm closing the issue and reopen in case we take this in consideration. Thanks.
