### ISSUE TITLE
Unable to open folder from desktop

### ISSUE THREAD

**Issue by Warstra** [spheras/desktopfolder#237]
### Description
Right clicking open or double clicking a folder or linked folder located on the desktop doesn't open. Other files types such as .pdf and .txt open still. If I go to my Desktop folder located in my Home directory right click open or double clicking opens the folder.

### Steps to reproduce
1. Right click on a folder or linked folder located on the desktop

or

2. Double click on a folder or a linked folder located on the desktop

### Expected result
The folder will open with the Files application.

### Actual result
Nothing happens.

### System Information
- OS: elementary OS 5 Juno
- Desktop Folder version: 1.0.10 Nov 7, 2018 Release

**Comment by spheras** [comment]
hello @Warstra. It sounds strange, and something specific from your installation. Could you check the following?:

1. First, open a terminal and run the following there
2. Kill the current desktopfolder process (sudo if necessary)
`killall com.github.spheras.desktopfolder`
3. enable debug messages:
`export G_MESSAGES_DEBUG=all`
4. start desktopfolder manually
`com.github.spheras.desktopfolder`

After that, try opening a folder and a text file from the desktop, and paste here all the debug messages at the console.

**Comment by spheras** [comment]
Ok, not sure if the xdg command is being executed, could you try to execute it manually to see if it is working?

xdg-open "/home/warren/Desktop/new file"

(there should be a "new file" in the Desktop)

If the new file is opened, could you try disabling the single_click with elementary tweaks?

**Comment by Warstra** [comment]
I created a "new file" on the desktop and ran the xdg command above and it opened. I disabled elementary single_click and it worked as well.

I did the exact same thing as above with a "new folder" (tried both with single_click on and off) and received the same error as before:

>  ** (io.elementary.photos:24843): CRITICAL **: 12:48:55.421: granite_message_dialog_construct_with_image_from_icon_name: assertion 'secondary_text != NULL' failed
> 
> (io.elementary.photos:24843): GLib-GObject-CRITICAL **: 12:48:55.421: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed
> 
> (io.elementary.photos:24843): Gtk-CRITICAL **: 12:48:55.421: gtk_window_set_transient_for: assertion 'GTK_IS_WINDOW (window)' failed
> 
> (io.elementary.photos:24843): Gtk-CRITICAL **: 12:48:55.421: gtk_dialog_run: assertion 'GTK_IS_DIALOG (dialog)' failed
> 
> (io.elementary.photos:24843): Gtk-CRITICAL **: 12:48:55.421: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
>

**Comment by spheras** [comment]
regarding folders, I think t is trying to open elementary photos application (not sure)... is it possible? What is your default application for file management? (look at system settings->applications)...

**Comment by spheras** [comment]
@Warstra, please, check if the file you are try to open have execution permissions. Perhaps that's the problem. Currently, when the file has execution permissions, the application try to "execute" it instead to open it. (that's something we will try to change)

**Comment by Warstra** [comment]
Sorry I forgot to close the issue. You were right for some reason it was trying to open with the picture application. Thank you for all your help.
