### ISSUE TITLE
Add appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [spheras/desktopfolder#247]
Translating appdata.xml file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by spheras** [comment]
mmm yes, I haven't thought this before.  So, do you think appdata.xml should be included in POTFILES.in? I'm not sure if this could be done for this release, it could affect a lot to the current translations (it will create a lot of untranslated texts). Maybe for the next one, don't you think @fossfreedom?
