### ISSUE TITLE
Drag file onto a folder creates a new file on the desktop

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#250]
split from #118

Action: Right click. Create a new folder. Right click - create a new file. Press CTRL and drag to the folder. 

Expected: the file is copied into the new folder

Actual result: A new file unexpectedly gets created on the desktop instead - no file is copied in the folder.

**Comment by spheras** [comment]
now folders items are treated as dropable elements... I mean, if you move an icon over a folder, it change the movement to a drag/drop action.. the folder element accepts to drop inside (Copy or move) the element moved.
