### ISSUE TITLE
Option to open links to folders as a panel.

### ISSUE THREAD

**Issue by Chronigan** [spheras/desktopfolder#261]
I use desktop folder to access the primary folders in my home directory, such as videos, documents, etc. What I think would be neat if instead of opening my file browser at that location, I had the option for a panel to be created with the items that reside in that folder, kind of like stacks that are in some docks.

This is mainly to bridge the gap between panels and folders. I don't use panels because they take up space and are always present.

**Comment by spheras** [comment]
Hi @Chronigan, thanks for reporting.  There are already similar issues like this (i.e. see #156). I think this is something we need to manage in next releases, some kind of panels iconized. I'm closing the issue, but is referenced, I will take into account, any way you are invited to add info/opinion into those existent issues.
