### ISSUE TITLE
Crash when dragging locked panel

### ISSUE THREAD

**Issue by srknzl** [spheras/desktopfolder#262]
### Description
A panel that is locked tried to be dragged and the application closed as unexpected.

### Steps to reproduce
1. Create a panel.
2. Select settings
3. Choose this panel tab
4. Press lock panel
5. Close the options box and try to drag the panel

### Expected result
Nothing should not happen. The application should be running afterwards. 

### Actual result
The application crashed without warning.
Cannot provide a screenshot as it does not make sense.

### System Information
- OS: elementary OS 0.5 Juno
- Desktop Folder version: 1.1.0

### Terminal output
Could not get any output.

**Comment by spheras** [comment]
Hi @srknzl.  Unortunately I can't reproduce the problem. I captured a gif reproducing the steps. Could you check if I did something different?
![blockpanel2](https://user-images.githubusercontent.com/3862933/54274961-b588fa80-4589-11e9-9b9f-ca845a1de5cd.gif)

**Comment by srknzl** [comment]
You did it right but I don't understand why it did not happen this time. I also tried again it did not happen. Wonder why, how can I debug this kind of an error? I was not be able to, because when I launch desktop folder from terminal it launches, and does not give any output.

**Comment by spheras** [comment]
I see. Probably there is something more to do to cause the crash.  Write this at the terminal before launching desktopfolder to see the output log:

`export G_MESSAGES_DEBUG=all`

At the [wiki](https://github.com/spheras/desktopfolder/wiki/Building-and-Running) you can find more info about debugging.
