### ISSUE TITLE
Cant build on Fedora 30+

### ISSUE THREAD

**Issue by tim77** [spheras/desktopfolder#269]
It complies fine in Fedora 29, but fail on Fedora 30 and Rawhide.

Fedora 29 [build log](https://copr-be.cloud.fedoraproject.org/results/atim/desktopfolder/fedora-29-x86_64/00909366-desktopfolder/builder-live.log)
* GCC version 8.3.1
* Vala version 0.42.7

---

Fedora 30 [build log](https://copr-be.cloud.fedoraproject.org/results/atim/desktopfolder/fedora-30-x86_64/00909373-desktopfolder/builder-live.log)
* GCC version 9.1.1
* Vala version 0.44.3

What can cause this?

**Comment by fossfreedom** [comment]
You'll need this commit in your build https://github.com/spheras/desktopfolder/commit/ae0cffad1f85349afafb23d68d7de90786a5642c

**Comment by tim77** [comment]
@fossfreedom works with this patch. Thank you!

**Comment by spheras** [comment]
can we close the issue?

**Comment by tim77** [comment]
Sure, thank you one more time.
