### ISSUE TITLE
Implement single click and respect Files single click settings

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#27]
By default Files uses single click to open/run files and folders. There's no UI to change this from elementary OS itself (which is intentional), however it can be changed using gsettings or the elementary tweaks tool.

Desktop Folder should read the settings for Files to determine whether to use single clicking or double clicking. (It will probably be single click most of the time.)

**Comment by spheras** [comment]
yes, you're right @aljelly. I didn't remembered that because the first thing I do with elementary is install tweaks and change this default behaviour to double click :laughing: 
I think it should be easy, probably as you said, just reading the files setting, I will search on tweaks source code.

**Comment by spheras** [comment]
@aljelly I found how to do it, is very easy, but now I realized that if I use only one click, then, how can I move icons? the only solution seems : release button without movement... whats your opinion?

**Comment by aljelly** [comment]
It looks like when you hold down the mouse on a file/folder in Files, there's a small area where you can move the mouse in and still open the file/folder when you let go of the mouse. But when you move the mouse outside of this area, it begins dragging the file/folder.

Maybe what I described [here](https://github.com/spheras/desktopfolder/issues/11#issuecomment-338118833) might be relevant (using a ghost/helper that follows your mouse when you drag an item rather than directly dragging the item around on the desktop).
