### ISSUE TITLE
Show desktop doesn't disable wingpanel's opaque state when window is maximized/tiled. 

### ISSUE THREAD

**Issue by Blast-City** [spheras/desktopfolder#270]
### Description
When a window is maximized, the winpanel (elementary's top panel) turns black. 
Show desktop doesn't disable the maximized opaque state

### Steps to reproduce
1- Open some apps.
2- Maximize one of the windows. The top panel changes from the normal state to being opaque black.
3- Press Super+D

### Expected result
When the desktop is shown, the top panel should turn to the normal state again.

### Actual result
The top panel stays black opaque even thought there is no windows showing on the screen.

### System Information
elementary OS Juno fully updated
Desktop Folder Ver. 1.1.1

**Notes:**
This issue is also happening on plank's desktop docklet and on wmctrl's show desktop command. Since Desktop Folder depends on the show desktop, maybe some Desktop Folder dev could report directly to elementary devs that the wingpanel should be aware when the desktop is shown so that all the apps (plank, wmctrl and desktop folder) are working as it should.

[More on this issue (GIF included)](https://github.com/elementary/wingpanel/issues/190)

**Comment by spheras** [comment]
thanks @Blast-City  for reporting. This is a curious issue. As you mentioned, I don't think this is a desktop folder issue. Yes, maybe we could report it directly to elementary devs. I will try to investigate, meanwhile, I will close this issue (as we can't do nothing from dekstop folder).  Don't hesitate to reopen if you see a solution (global solution, as this app is not only for eos) or can add more info.

thanks!
