### ISSUE TITLE
Tooltips and locking screen breaks show desktop.

### ISSUE THREAD

**Issue by Blast-City** [spheras/desktopfolder#271]
### Description
After showing the desktop It's not possible to bring back windows if a tooltip appears on the screen. The same happens if the screen is locked after showing the desktop

### Steps to reproduce
1- Open some apps.
2- Press Super+D
3- Hover a dock icon or the applications icon on the top panel until a tooltip is shown
4- Press Super+D again

### Expected result
The windows should be shown again 

### Actual result
Pressing Super+D doesn't show the hidden windows again.

### System Information
elementary OS Juno Fully updated
Desktop Folder Ver. 1.1.1

**Notes:**
This issue is also happening on plank's desktop docklet and on wmctrl's show desktop command. Since Desktop Folder depends on the show desktop, maybe some Desktop Folder dev could report directly to elementary devs that the wingpanel should be aware when the desktop is shown so that all the apps (plank, wmctrl and desktop folder) are working as it should..

[More on this issue (GIF included)](https://github.com/elementary/gala/issues/452)

**Comment by spheras** [comment]
Hi @Blast-City, thanks for reporting. Interesting bug too. Unfortunately, I don't know what we could do from desktopfolder, as we only use standards GTK functions to show the desktop. I think you did the correct reporting it to elementary.  Anyway, any help is more than welcome, if you have some ideas to fix this behaviour from the application, don't hesitate to reopen the issue.  Thanks again!
