### ISSUE TITLE
 Note font color on Elementary OS cannot be set to black

### ISSUE THREAD

**Issue by envieme** [spheras/desktopfolder#272]
On Elementary OS Juno, new notes text color cannot be set. It is always light gray. Other things like header text color, background color, background paper texture all can be set.

![](https://user-images.githubusercontent.com/1422393/58773799-0e988580-85f1-11e9-84d3-39a681277731.png)

**Comment by spheras** [comment]
hi @envieme, thanks for reporting. Yes, it seems a bug, you should be able to change the text color to black and white (as the title).

**Comment by spheras** [comment]
The issue was solved. Hope next version will be pushed soon to eos app center.

**Comment by mariadb-ThienLy** [comment]
Seems only the title's colour can be changed. The body text always white
