### ISSUE TITLE
Add Preferences dialog

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#28]
Perhaps when you right click on the desktop (i.e. not on a panel or photo or note), a Preferences page could show as a menu item.

This is what the Preferences page for Scratch looks like for reference:

![2017-10-21 09_44_17-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/31850126-40dd8ffe-b645-11e7-8b3e-8e4fbd2306d6.png)

Maybe it could look like that?

**Comment by spheras** [comment]
Yes, we start needing something like that. Not sure if it is necessary to hide the settings item menu, but we must decide what configuration is on the menu or not.. i.e. colors shown on the popup, or in prefferences window? (in my opinion the popup is beautiful with the color selection)

**Comment by aljelly** [comment]
I think the application should be designed to keep things out of a preferences dialog as much as possible; we should only add a preferences dialog when something really needs to go there and wouldn't make sense in any other context.

For example, instead of adding "Icon size" to a preferences panel, we should instead use Ctrl + Mouse Scroll or Ctrl + Plus/Minus to change the icon size.

Currently I don't think we need a preferences dialog because there's nothing to put in it.

I think it would be ideal to keep most options in the context menu.

**Comment by spheras** [comment]
I'm trying to summarize what can be configured for a panel today (to decide what must be outside of the popup):

- Text Color
- Text Shadow
- Text Bold
- Background Color

What I miss ordered by importance:
- Custom Color
- Background Transparency
- Icons Size (not too much important for me)

I don't see now what more configuration should be needed in the future. I mean, probably thats enough to make happy 90% of the people. What configuration of this you think shouldn't be there? or at least, what configuration shouldnt be shown at the popup.

**Comment by jica** [comment]
Other options could be:

. The font size/family of the note panels.
. Header height (not possible by now).
. Single/double click or system configuration. There are people who don't
know how to change file settings.

**Comment by aljelly** [comment]
See #33 for ideas on customisation of appearance.

I disagree with adding a single/double click option though.

**Comment by spheras** [comment]
what is the status of this issue? I've seen @aljelly  you have done some kind of PanelProperties Dialog. Are you still working on it? Do we need to decide/think anything more from the wiki page?

**Comment by spheras** [comment]
I did a first aproximation of this dialog
