### ISSUE TITLE
Feature Request: View files by pressing Spacebar

### ISSUE THREAD

**Issue by a-tokarev** [spheras/desktopfolder#282]
Currently, to view files (such as images) on my Desktop, I have to double-click them (which launches system image viewer). Is it possible to view files by selecting via mouse and pressing Spacebar (macOS-style)?

If this feature does not exist currently in Desktop Folder, is it possible to implement it?

**Comment by spheras** [comment]
Hi @a-tokarev. You can now press enter to show the image, not necessarily by double clicking. Did you tried that?

**Comment by a-tokarev** [comment]
Yes, but pressing Enter isn't any more convenient or quick than double-clicking. Because Enter key is located much farther on the keyboard and cannot be pressed with the left hand without a) lifting it from the keyboard and b) looking on the keyboard to locate it. In comparison, I can press the Spacebar key much faster: without looking at the keyboard and without lifting my left hand.

**Comment by aljelly** [comment]
Probably this would be best solved by having space bar do the same thing as the enter key. That's probably easy to add.
