### ISSUE TITLE
Ability to unlink the "Link Panel"

### ISSUE THREAD

**Issue by v4i1n1a9y8** [spheras/desktopfolder#285]
Suppose if i use "Link Panel" option to create a panel with contents of documents folder, it will create symlink of documents folder in the desktop folder. However there is no way to graphically unlink this panel other than "Move to trash" option. 

Could there be an icon to unlink the panel next to the "Move to trash" icon.
or
Option to unlink the panel in the right click menu.

**Comment by fossfreedom** [comment]
"Move to tras"h sounds correct - what do you think should happen if you "unlink panel" ?  Sounds like you would be left with an empty panel on the desktop.

**Comment by v4i1n1a9y8** [comment]
But the "Move to trash" option is deleting the actual folder rather than the symlink. What if i want to just remove the panel but keep the Documents folder in its place? 

After creating a "Link Panel" of Documents folder, a symlink appears. But the "Move to trash" option deletes the actual folder. Here's the terminal equivalent of what i actually expect in the "unlink panel" option:-
![Screenshot from 2019-11-25 20-40-55](https://user-images.githubusercontent.com/35867832/69552275-2eb76900-0fc4-11ea-8f8d-b17ceb7f8f1f.png)

**Comment by fossfreedom** [comment]
ah ... definitely wrong.

**Comment by v4i1n1a9y8** [comment]
Sorry. just tried it on elementary and.... it works as expected!
I was using the flatpak build i created and that could be the source of problem.

**Comment by v4i1n1a9y8** [comment]
tried manually building on fedora31 and it also works as expected.(trashing the symlink instead of actual folder)
So the source of the problem was in the flatpak build. There might be some problem with trash portal in flatpak.
