### ISSUE TITLE
Don't allow renaming panels to invalid folder names

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#29]
Renaming a Panel to `/` causes Desktop folder to be shown, and if you rename the panel to `../`, you can view the home folder. You can basically show any directory you want in a panel with this. Here's root:

![2017-10-21 11_12_43-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/31850796-cee7cf48-b650-11e7-8db5-a1063b890025.png)

Look at [this comment](#issuecomment-338515449) for more info. This should probably also check names of new panels.

(This issue is specifically about the bug, the feature request for creating "link panels" is at #32.)

**Comment by spheras** [comment]
Did you know that you can create a link on your desktop folder and the app will create a Panel? (you must restart the app to create the "link panel")

**Comment by aljelly** [comment]
I didn't know you could do that, that works quite well. I created an issue for allowing creation of "link panels" at #32.

Meanwhile this issue will specifically be about the fact you can rename panels to `/` and `../`, which can lead to unexpected behavior:

- Renaming a folder to a path that points somewhere else, like `../../Pictures` (aka `~/Pictures`) and then renaming again to a valid folder name, like "My Panel For Pictures" will move the Pictures folder to the Desktop directory with the new name (`~/Desktop/My Panel For Pictures`). This is obviously not intended behavior.

The solution to this is to not allow renaming panels to invalid folder names.
