### ISSUE TITLE
Not working on ElementaryOS Version 5.1.3

### ISSUE THREAD

**Issue by paulbreitner** [spheras/desktopfolder#295]
I have ElementaryOS Version 5.1.3 now. But the Desktop/Folder app is not working for me. 
Does anyone else have the problem?

**Comment by paulbreitner** [comment]
I solved it: 

System Settings > Mouse & Touchpad > Physical clicking (in the Touchpad area)

And then I selected "Hardware default" in order to have it working.

**Comment by spheras** [comment]
Thankyou @paulbreitner, it is great to have this info here for any other people that could have a similar problem.
Cheers!
