### ISSUE TITLE
Icons disappear when changing desktop

### ISSUE THREAD

**Issue by Gabriel-AB** [spheras/desktopfolder#296]
### Description

Icons disappear when switching desktops, visual problem

### Steps to reproduce
On elementary os
1. Super + →
2. Super + ←

### Expected result
if it shouldn't appear on both screens, at least the first one should keep the app view

### Actual result
The right click and double click still works but the icons desappear 

![Screen record from 2020-04-11 11 44 56](https://user-images.githubusercontent.com/56075236/79046920-f23e7f80-7be9-11ea-976a-153f7a69cc87.gif)

### System Information
- OS: elementary OS 5.1.3 Hera
- Desktop Folder version: 1.1.2

### Terminal output

$ env G_MESSAGES_DEBUG=all com.github.spheras.desktopfolder
(com.github.spheras.desktopfolder:6428): Gtk-DEBUG: 11:34:52.253: Connecting to session manager
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.255: Application.vala:99: startup event
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.255: Application.vala:86: activate event
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.256: Application.vala:239: show_desktoppanel: true
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: FolderManager.vala:259: Monitoring: /home/gabriel/Desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: DesktopWindow.vala:97: trying to hide
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: DesktopManager.vala:83: hide_items false
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: DesktopManager.vala:84: hiding items
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: FolderManager.vala:1106: >>>>>>>>>>> INIT _sync_files for Panel: 
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.393: FolderManager.vala:1114: >>>>>>>>>>>>>>>>>>>>>>>RESTARTING _sync_files 0 times for Panel 
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//Hitman Blood Money.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//CS2D.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//TowerFall Ascension.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//Brawlhalla.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//Super Crate Box.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.394: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//UNO.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.395: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//Garry's Mod.desktop
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.395: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//.desktopfolder
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.395: FolderManager.vala:1149: syncing file found:/home/gabriel/Desktop//folder
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.797: DesktopWindow.vala:97: trying to hide
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.797: DesktopManager.vala:83: hide_items false
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.797: DesktopManager.vala:84: hiding items
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.798: DesktopWindow.vala:97: trying to hide
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.798: DesktopManager.vala:83: hide_items false
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.798: DesktopManager.vala:84: hiding items
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.798: FolderManager.vala:1281: >>>>>>>>>>> END _sync_files for Panel: 
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.799: DesktopManager.vala:149: Dock window found: wingpanel
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.827: DesktopManager.vala:149: Dock window found: plank
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.849: DesktopManager.vala:128: DESKTOP SIZE CHANGED! (0,0) (1360,768)
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:52.859: Application.vala:571: Monitoring: /home/gabriel/Desktop

** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:53.428: Application.vala:637: desktop_visible is now true
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:34:53.428: DesktopWindow.vala:94: refresh, icons enabled and desktop visibility = true
** (com.github.spheras.desktopfolder:6428): DEBUG: 11:35:03.894: FolderWindow.vala:1039: event key 65513

**Comment by jonklinger** [comment]
can confirm and reproduce here.

**Comment by rengare** [comment]
Well I found out that they don't disappear, they are just transparent
![Screenshot from 2020-04-22 10-56-59](https://user-images.githubusercontent.com/10849982/79962191-0d31af00-8488-11ea-8ee4-ca71ffac07e0.png)

**Comment by rengare** [comment]
Im working on workaround ;)

**Comment by gkdgoutam** [comment]
Same problem with even no right click. The desktop is showing only for the first boot. After that when switching workspaces it disappears competely from all workspaces even from the first workspace on eOS HERA-5.1.3.

**Comment by javogarcia** [comment]
I'm confirming this issue on Hera 5.1.3. I'm too ignorant for fixing. @rengare our faith is on you 🙏️.

**Comment by rengare** [comment]
I have created a workaround for the issue. If you are in a hurry you can grab my branch and compile the code. ([branch link](https://github.com/rengare/desktopfolder/tree/missing_desktop_when_workspace_changed))

**Comment by spheras** [comment]
I'm reopening the issue as I experienced problems when changing the workspace very fast. The system seems to crash sometimes. Looking for a solution.

**Comment by rengare** [comment]
@spheras no but I didn't change workspace fast, indeed there is a problem.

**Comment by rengare** [comment]
@spheras 
When you use this code, it not crash anymore, until you uncomment 
`this.sync_folders_and_notes();`. Maybe it will be helpful for you, my laptop's battery is off so I'll try to fix it in the evening or tomorrow

```
private void on_workspace_change(Wnck.Workspace? previous) {
        Timeout.add (500, () => {
            this.hide_everything ();
            
            this.clear_folders ();
            this.clear_notes ();
            this.clear_photos ();

            this.desktop_visible = false;
            this.desktop = null;
            return false;
        });
        Timeout.add (1000, () => {
            this.desktop_visible = true;
            this.desktop = new DesktopFolder.DesktopManager (this);
            
            this.show_everything ();
            //  this.sync_folders_and_notes();
            return false;
        });
    }
```

**Comment by spheras** [comment]
thanks @rengare, in my case, with this function, it continue freezing (and crashing sometimes) the laptop when I change the workspace rapidly.  I'm trying to find the source of the problem. It is interesting to see how the gtk inspector is able to show again the parent desktop window, simply modifying the visible property.

**Comment by spheras** [comment]
@rengare, I did some changes to avoid crashing and simplifying a lot the solution.  
1. Simply changing the visibility from false to true 
2. Taking care of the thread created to remove it if another change is performed 

It seems to work properly here, could you check a bit to ensure it is correct? Thx!

**Comment by rengare** [comment]
Sure I'll do that :)

**Comment by rengare** [comment]
On VM it sometimes crashes but it works fine on the real machine

**Comment by spheras** [comment]
Ok, thx!, I think we can close the issue for now.
This issue is strange, and it seems really an issue for the window manager (gala), or something like that.  I would like to know if this occurs also with other window managers.
