### ISSUE TITLE
Show volumes?

### ISSUE THREAD

**Issue by Ratteler** [spheras/desktopfolder#303]
I don't see it anywhere, so sorry if I missed it.
I would like to see all my volumes (Drives, Partitions) automatically show up on my desktop.
This is especially needed for removable media like USB thumb drives and SD Cards.

Great Project by the way. One of the reasons I chose Elementary OS was this project!

**Comment by spheras** [comment]
Hi @Ratteler, thanks for reporting. Yes, I like the idea. This was asked already at #152. Take a look at that issue, I will try to gather some new features for the next big release (If I find enough free time).
If you don't mind, we can continue the conversation (if needed) there, and mark this as duplicated.
