### ISSUE TITLE
Installation on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by marcmaj** [spheras/desktopfolder#307]
Installing fails with following error:
`sudo dpkg -i com.github.spheras.desktopfolder_1.1.2_amd64.deb`

> Selecting previously unselected package com.github.spheras.desktopfolder.
> (Reading database ... 340315 files and directories currently installed.)
> Preparing to unpack com.github.spheras.desktopfolder_1.1.2_amd64.deb ...
> Unpacking com.github.spheras.desktopfolder (1.1.2) ...
> Setting up com.github.spheras.desktopfolder (1.1.2) ...
**> dpkg: error processing package com.github.spheras.desktopfolder (--install):
>  installed com.github.spheras.desktopfolder package post-installation script subprocess was killed by signal (Terminated)**
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for libglib2.0-0:i386 (2.64.2-1~fakesync1) ...
> Processing triggers for libglib2.0-0:amd64 (2.64.2-1~fakesync1) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Errors were encountered while processing:
>  com.github.spheras.desktopfolder

**Workaround:**
Only way to install desktopfolder is to manually edit postinst script i.e. `/var/lib/dpkg/info/com.github.spheras.desktopfolder.postinst` and remove this line:
`killall com.github.spheras.desktopfolder`. After that `sudo apt install -f` and app is installed.

Removing is similar, first edit `/var/lib/dpkg/info/com.github.spheras.desktopfolder.prerm` and remove this line:
`killall com.github.spheras.desktopfolder`
then `sudo apt purge com.github.spheras.desktopfolder`

**Comment by fossfreedom** [comment]
BTW - v1.1.2 is available in the normal ubuntu repositories

    sudo apt install desktopfolder

**Comment by spheras** [comment]
Thank you @marcmaj  for reporting.  @fossfreedom, did you remove/replace that line too in budgie branch? What is your advice about that? Thx!

**Comment by fossfreedom** [comment]
I don't have any additional installation scripts for debian & ubuntu

https://github.com/UbuntuBudgie/desktopfolder/tree/debian/debian

I didn't see any reasons to include them.

**Comment by spheras** [comment]
I removed those scripts from the deb installation
