### ISSUE TITLE
Where to put the collaborators info?

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#31]
We don't have now an about dialog, and I would like to put your names with the application for the next release (1.0.2). The only place I've found is at the appcenter metadata info (data/com.github.spheras.desktopfolder.appdata.xml)... There, we have a "developer_name", single :(, I was thinking to put there all the names, but I'm afraid it is not a long field. The only way I see is to put "desktopfolder developers"..  Any ideas? @aljelly @jica @welaq

**Comment by lainsce** [comment]
You can use the AUTHORS.md file on the root here on your repository to reference any people that helped you, but put yourself as the first line.

**Comment by aljelly** [comment]
Done. @spheras close this if you're happy with this.

**Comment by spheras** [comment]
Ok, thanks @lainsce for your comment.
