### ISSUE TITLE
"Link panel" feature

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#32]
Link panels (name not final, Fences calls them "Portals") would allow the user to create panels that show the contents of any folder on their system, as long as they have write permissions for the folder (at least for the moment, as without write permissions, the .desktopfolder file can't be created).

The implementation is simple: create a link in the Desktop folder that points to the desired folder. It can already be done manually, it just needs a way to be done through the software.

Currently, if you do it manually and get the software to refresh (e.g. renaming a panel), all the items in the panel are stacked on top of each other in the top left corner. So when a new folder or link is found and it doesn't have a .desktopfolder file in it, the folder contents need be spread out, preferably to the grid.

It might also be worthwhile to think about what will happen if a link panel is deleted. Should the link be deleted instead of being sent to the Trash? There probably wouldn't need to be any warning because only the link is deleted. No data is lost: the link can be recreated.

**Comment by spheras** [comment]
Yes, it is an easy functionality that we must do. Should we highlight that the panel is a link some way?? putting an icon or something? you know, files have an arrow below. I think that it could be important to know if you are dealing with the folder directly or just a link to a folder.
Portal is a very good name. Can we use too? or is registered :P

**Comment by aljelly** [comment]
Maybe put the link icon (an arrow) to the left or right of the panel name in the title bar?

**Comment by spheras** [comment]
Yes, that could be fine

**Comment by spheras** [comment]
I added an option under the new submenu, "Link Panel". This is how it looks a Link Panel
![captura realizada el 2017-10-27 22 40 44](https://user-images.githubusercontent.com/3862933/32124779-5578e386-bb69-11e7-99b0-0916c150604b.png)
