### ISSUE TITLE
dpkg: error processing package com.github.spheras.desktopfolder (--remove)

### ISSUE THREAD

**Issue by mihkuno** [spheras/desktopfolder#324]
There was some buggy duplication of icons so I tried removing desktopfolders with apt remove then this showed up

Removing com.github.spheras.desktopfolder (1.1.2) ...
dpkg: error processing package com.github.spheras.desktopfolder (--remove):
 installed com.github.spheras.desktopfolder package pre-removal script subprocess was killed by signal (Terminated)
dpkg: too many errors, stopping
dpkg: error while cleaning up:
 installed com.github.spheras.desktopfolder package post-installation script sub
process was killed by signal (Terminated)
Errors were encountered while processing:
 com.github.spheras.desktopfolder
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)

and since i can't remove it, i also cant start it with com.github.spheras.desktopfolder anymore and says its not found
- so i can't post a picture abt that buggy icon duplicate.. and i'm sure it's not the desktop icons gnome extension since i removed it before then

**Comment by bloxerian** [comment]
sudo rm -r /var/lib/dpkg/info/com.github.spheras.desktopfolder.*
sudo apt-get clean && sudo apt-get update
sudo apt-get remove com.github.spheras.desktopfolder
sudo apt-get purge com.github.spheras.desktopfolder
sudo apt remove com.github.spheras.desktopfolder

i hav no idea what i did.. but fixed it ;3
