### ISSUE TITLE
Multitasking view 

### ISSUE THREAD

**Issue by pavlepiramida** [spheras/desktopfolder#34]
![screenshot from 2017-10-23 11 25 58](https://user-images.githubusercontent.com/18991480/31881824-090520b4-b7e5-11e7-9c43-d3382f4a0466.png)

I dont know if anyone else reported this or is it just me,but as you can see panels are floating over overview.
The issue is bound to panel (havent tried photos feature).

Hope this helps you a bit.
Also issue is super easy to reproduce,just spawn new panel and open multitasking.

**Comment by aljelly** [comment]
It's already fixed at #7, but thanks for reporting. The fix should come with the next update.
