### ISSUE TITLE
Restore minimized windows when Super + D is pressed again

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#43]
Restore minimized windows if Super + D is pressed a second time and no other windows have been restored since (or focus hasn't been lost to a non-Desktop Folder window).

**Comment by spheras** [comment]
I think this is easy to implement. My concern is how this will be done in Wayland (currently it is done with Wnck library)

**Comment by spheras** [comment]
@aljelly, this is how it is done in plank:

```vala
unowned Wnck.Screen screen = Wnck.Screen.get_default ();
screen.toggle_showing_desktop (!screen.get_showing_desktop ());
```

https://github.com/ricotz/plank/blob/ed80c130135f7ca7bd112203e17c00086f58108c/docklets/Desktop/DesktopDockItem.vala

**Comment by eljefuri** [comment]
@spheras Is this actually implemented in the current Desktop Folder or was there some kind of regression? It doesn't appear to work anymore, so maybe this issue should be opened again?

**Comment by spheras** [comment]
It works now. The problem maybe is that you click over panels or desktop. If you click I can't return. This is done automatically by the system. I'm not sure if we could do something better by code.
