### ISSUE TITLE
Fix uncrustify and/or uncrustify config

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#49]
It's doing this currently:

```vala
this.timeout_id = GLib.Timeout.add (100, () => {
                                                // this.prueba.set_text("prueba %d".printf(this.index));
                                                (this.progress_bar as Gtk.ProgressBar).pulse ();
                                                (this.status as Gtk.Label).set_text (this.text);
                                                return true;
                                            });
```

But maybe it should be like this:

```vala
this.timeout_id = GLib.Timeout.add (100, () => {
    // this.prueba.set_text("prueba %d".printf(this.index));
    (this.progress_bar as Gtk.ProgressBar).pulse ();
    (this.status as Gtk.Label).set_text (this.text);
    return true;
});
```

Should it be configured to do that instead?

(Add any other comments about the code style and the config here)

**Comment by spheras** [comment]
From my understanding, yes, the second one is much better, mainly because one important restriction is the line length, which is the typical configuration of 120 chars

> Columns per line
> 
> Ideally, lines should have no more than 80 characters per line, because this is the default terminal size. However, as an exception, more characters could be added, because most people have wide-enough monitors nowadays. The hard limit is 120 characters.

**Comment by aljelly** [comment]
The config now works with `_(` so it can be run on `LanguageText.vala` now.

**Comment by spheras** [comment]
this issue is closed, isn't it?

**Comment by aljelly** [comment]
There seems to be a strange mismatch between when I run uncrustify and when you run uncrustify. Yours seems to be doing this:

```diff
public PanelProperties (FolderWindow window) {
              Object (
                  border_width: 5,
-                 deletable:    false,
-                 resizable:    false,
-                 title:        _("Properties")
+deletable:    false,
+resizable:    false,
+title:        _("Properties")
              );
          }
```

It seems if a property is set to a number, it doesn't do this, but if it's a string or bool, it moves it to the beginning of the line.

It seems mine isn't affected by this and corrects it when I run it again:

```diff
         public PanelProperties (FolderWindow window) {
             Object (
                 border_width: 5,
-deletable:    false,
-resizable:    false,
-title:        _("Properties")
+                deletable:    false,
+                resizable:    false,
+                title:        _("Properties")
             );
         }
```

---

But when I run it, it does this:

```diff
 public class DesktopFolder.ProgressDialog : Gtk.Dialog {
-    private Gtk.Widget       status;
-    private Gtk.Widget       progress_bar;
-    private Gtk.Box          window_vbox;
-    private uint             timeout_id = 0;
+    private Gtk.Widget status;
+    private Gtk.Widget progress_bar;
+    private Gtk.Box window_vbox;
+    private uint timeout_id = 0;
     private GLib.Cancellable cancellable;
 
     /**
```

And this:

```diff
 public class DesktopFolder.PhotoSettings : Object {
-    public int    x  { get; set; default = 0; }
-    public int    y  { get; set; default = 0; }
-    public int    w  { get; set; default = 0; }
-    public int    h  { get; set; default = 0; }
-    public int    original_width { get; set; default = 0; }
-    public int    original_height { get; set; default = 0; }
-    public int    fixocolor { get; set; default = 0; }
+    public int x  { get; set; default = 0; }
+    public int y  { get; set; default = 0; }
+    public int w  { get; set; default = 0; }
+    public int h  { get; set; default = 0; }
+    public int original_width { get; set; default = 0; }
+    public int original_height { get; set; default = 0; }
+    public int fixocolor { get; set; default = 0; }
     public string name { get; set; }
     public string photo_path { get; set; }

```

---

The problem is it creates a lot of noise if our uncrustifying keeps changing these back and forth.

Maybe we're running different versions? I built uncrustify from the [latest release](https://github.com/uncrustify/uncrustify/releases/tag/uncrustify-0.65). I get `Uncrustify-0.65_f` when running `uncrustify --version`.

Did you use `sudo apt install uncrustify`? It looks like the latest published version for Ubuntu Xenial (elementary's base) is outdated (version 0.59). I tried the version from `sudo apt install uncrustify` and it looks like it's doing what your version is doing.

I could add instructions for building the [latest release](https://github.com/uncrustify/uncrustify/releases/tag/uncrustify-0.65) of uncrustify to the `knowhow` file, so everyone is using the same version.

**Comment by spheras** [comment]
Yes, youre right :smile: I did an apt install (0.59). Don't worry, I'll install from 0.65.

**Comment by aljelly** [comment]
I added an [Uncrustifying](https://github.com/spheras/desktopfolder/wiki/Uncrustifying) page to the wiki with instructions to easily install it.

**Comment by spheras** [comment]
Ok, great. Mine is already updated:
$ uncrustify --version
Uncrustify-0.65_f

**Comment by spheras** [comment]
I've just pushed after the update of uncrustify, hope everything is OK now.

**Comment by aljelly** [comment]
Yes, it's good now. I tried running it and makes no extra changes to the current code. We shouldn't have any more problems with mismatching output.

And since we now have simple instructions for installing and using uncrustify 0.65, it should be easy for future contributors to use it as well.
