### ISSUE TITLE
Some launcher icons make the item appear too big

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#54]
![2017-10-29 06_25_19-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/32141207-1185507e-bc72-11e7-81ee-0da3c0328bd4.png)

Not sure if this applies to anything other than launchers.

---

The grid still regards the item as the same size though, it just appears larger:

![2017-10-29 06_28_26-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/32141219-94cce42e-bc72-11e7-9797-47e591504543.png)

**Comment by spheras** [comment]
could you attach some example of .desktop file here? I can't reproduce the issue

**Comment by aljelly** [comment]
The two enlarged apps shown there are from the elementary AppCenter: Bottles and News.

**Comment by spheras** [comment]
gicons are now checked to get the correct dimmension (if the app doesn't provided it)
