### ISSUE TITLE
No null checks for Folder/Note/Photo Settings read_settings () method

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#59]
There seems to be no check for PhotoSettings being null if it catches an error and returns `null`.

Download [this invalid image](https://user-images.githubusercontent.com/10395308/32141515-69f2ff42-bc7a-11e7-950e-f8cf3db70a42.png). Name it `invalid.png`. Create `invalid.png.dfp` outside of `~/Desktop/` and fill it's contents with this, editing the path to point to the image:

```json
{"x":110,"y":110,"fixocolor":5,"name":"invalid.png","photo-path":"/home/USER/Pictures/invalid.png"}
```
Now move `invalid.png.dfp` inside `~/Desktop/`.

When the invalid image is read:
1. `Application.vala` line 193: Finds a new photo (the invalid photo) and goes to `PhotoManager.vala`.
2. `PhotoManager.vala` line 47: Calls `this.load_photo_settings ()`.
3. `PhotoManager.vala` line 76: `this.load_photo_settings ()` goes to `PhotoSettings` `read_settings ()`.
4. `PhotoSettings.vala` line 117: `read_settings ()` tries to read the invalid image.
5. `PhotoSettings.vala` lines 124-125: It throws an error because it can't. PhotoSettings returns null.

There are no checks for PhotoSettings being null from this error beyond this point. Both PhotoManager and `Application.vala`'s `sync_folders_and_notes ()` carry on assuming everything went fine.

The dfp file should probably be deleted if a problem is found.

**Comment by aljelly** [comment]
In fact I suspect null/error checks are missing in various places. Look at this:

![2017-10-30 10_17_12-](https://user-images.githubusercontent.com/10395308/32165702-91233dde-bd5b-11e7-82c5-2ace4ed49b2f.png)

This is what you get when you mess up the `.dfn` json file. Output:

```
** (com.github.spheras.desktopfolder:6256): DEBUG: NoteManager.vala:72: loading note settings.../home/aled/Desktop/Error time.dfn
Error: <data>:1:11: Parse error: unexpected identifier `setrdyullow', expected value

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_w: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_x: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_y: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_bgcolor: assertion 'self != NULL' failed

(com.github.spheras.desktopfolder:6256): Gtk-CRITICAL **: gtk_style_context_add_class: assertion 'class_name != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_fgcolor: assertion 'self != NULL' failed

(com.github.spheras.desktopfolder:6256): Gtk-CRITICAL **: gtk_style_context_add_class: assertion 'class_name != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_text: assertion 'self != NULL' failed

(com.github.spheras.desktopfolder:6256): Gtk-CRITICAL **: gtk_text_buffer_set_text: assertion 'text != NULL' failed
** (com.github.spheras.desktopfolder:6256): DEBUG: Application.vala:329: Monitoring: /home/aled/Desktop


** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_texture: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_clipcolor: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_texture: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_texture: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_get_text: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_set_text: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:6256): CRITICAL **: desktop_folder_note_settings_save: assertion 'self != NULL' failed
```

Even though it's unlikely someone will come across this, it should still be checked.

**Comment by aljelly** [comment]
FolderSettings is also affected (all Settings classes are affected). Output is similar to notes but with FolderSettings variables instead. They also look similar:

![2017-10-30 11_10_35-elementary os running - oracle vm virtualbox](https://user-images.githubusercontent.com/10395308/32168072-0a6c9a1c-bd63-11e7-9c4b-18fa8dc6019f.png)

- The white box is a folder with permissions `000`.
- "Restricted permissions to settings file" is a folder with `.desktopfolder` file file set with permissions `000`.
- The third has an invalid `.desktopfolder` file (replaced a part of it with random text).

**Comment by spheras** [comment]
I've made some modifications to control errors when loading settings. In the case of panels we can recreate a settings with default value is something bad happen.. for Notes and Photos, the settings file is removed (trash).  Please, check if everything is OK.
