### ISSUE TITLE
 script-without-shebang

### ISSUE THREAD

**Issue by awissu** [spheras/desktopfolder#69]
Hi! 
I want to inform you about the found problems when building RPM:

> desktopfolder.x86_64: W: script-without-shebang /usr/share/icons/hicolor/48x48/apps/com.github.spheras.desktopfolder.svg
> desktopfolder.x86_64: W: script-without-shebang /usr/share/icons/hicolor/64x64/apps/com.github.spheras.desktopfolder.svg
> desktopfolder.x86_64: W: script-without-shebang /usr/share/icons/hicolor/16x16/apps/com.github.spheras.desktopfolder.svg
> desktopfolder.x86_64: W: script-without-shebang /usr/share/icons/hicolor/128x128/apps/com.github.spheras.desktopfolder.svg
> This text file has executable bits set or is located in a path dedicated for
> executables, but lacks a shebang and cannot thus be executed.  If the file is
> meant to be an executable script, add the shebang, otherwise remove the
> executable bits or move the file elsewhere.

**Comment by spheras** [comment]
Hi @awissu, this error is generating the rpm? or installing a rpm? I've just created a test rpm from the provided .deb (alien tool), and it seems to be created correctly (I don't know if it works).   The error you report say something about the svg files which aren't executables, no idea why.. How could I reproduce the problem? What SO are you trying to check (please, take into account that unfotunately desktopfolder doesn't work on wayland)

**Comment by awissu** [comment]
> Hi @awissu, this error is generating the rpm?

This warning from RPMlint in OBS.
More info: https://build.opensuse.org/public/build/home:awissu:branches:X11:Pantheon/openSUSE_Tumbleweed/x86_64/desktopfolder/_log

> unrpm -v desktopfolder-1.0.2-6.1.i586.rpm
> desktopfolder-1.0.2-6.1.i586.rpm:	./etc/xdg/autostart/com.github.spheras.desktopfolder.desktop
> ./usr/bin/com.github.spheras.desktopfolder
> ./usr/share/appdata
> ./usr/share/appdata/com.github.spheras.desktopfolder.appdata.xml
> ./usr/share/applications/com.github.spheras.desktopfolder.desktop
> ./usr/share/doc/packages/desktopfolder
> ./usr/share/doc/packages/desktopfolder/AUTHORS.md
> ./usr/share/doc/packages/desktopfolder/LICENSE
> ./usr/share/doc/packages/desktopfolder/README.md
> ./usr/share/glib-2.0/schemas/com.github.spheras.desktopfolder.gschema.xml
> ./usr/share/icons/hicolor/128x128/apps/com.github.spheras.desktopfolder.svg
> ./usr/share/icons/hicolor/16x16/apps/com.github.spheras.desktopfolder.svg
> ./usr/share/icons/hicolor/48x48/apps/com.github.spheras.desktopfolder.svg
> ./usr/share/icons/hicolor/64x64/apps/com.github.spheras.desktopfolder.svg

> 
> ls -l usr/share/icons/hicolor/128x128/apps/com.github.spheras.desktopfolder.svg
> -rwxr-xr-x 1 awissu users 19136 окт 26 01:00 usr/share/icons/hicolor/128x128/apps/com.github.spheras.desktopfolder.svg

**Comment by spheras** [comment]
thank you @awissu, I removed the executable permissions for the svg files.
