### ISSUE TITLE
Use .desktopnote/.desktopphoto rather than .dfn/.dfp

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#75]
A user is much more likely to understand what a `.desktopnote`/`.desktopphoto` file is than a `.dfn`/`.dfp` file when they look in their Trash or `~/Desktop` folder.

### Summary
- Change `.dfn`/`.dfp` to `.desktopnote`/`.desktopphoto`
- Retain backwards compatability with .dfn and .dfp

**Comment by spheras** [comment]
Now .desktopnote and .desktopphoto are the new extensions used for new photos and notes. The application remains using the old extensions for backward compability.
