### ISSUE TITLE
Panel disappeared

### ISSUE THREAD

**Issue by MontAle** [spheras/desktopfolder#77]
I accidentally moved out "out of the screen" the only panel I had, and have no way to bring it back. Even uninstalling and reinstalling do nothing, so, no panel shows on my desktop

**Comment by spheras** [comment]
Hi @MontAle, this is something we have been fixing (see issue #64) for the next release.  

If you don't have any other option (maybe you have a two monitors configuration and the folder is there, or a different resolution)... you can always open directly the json file and reposition manually the folder.  All the panels are under your home directory   ~/Desktop.  Inside there you can find more folders (panels) and/or notes (*.dfn)  and/or photos (*.dfp).  In the case of folders (i.e.  ~/Desktop/myfolder), you can see inside a hidden file  (.desktopfolder) which maintain the configuration of the folder. So, you can edit it and bring back manually to other position:

`$ nano ~/Desktop/myfoldername/.desktopfolder`

then you will see something similar to:

`{"x":30,"y":30,"w":330,"h":406,"name":"myfoldername","bgcolor":"df_black","fgcolor":"df_light","textbold":true,"textshadow":true,"items":["new.txt;77;96;"]}`

Probably you have an invalid x,y position there. Modify those parameters and save (in nano Ctrl-x, and then Y to save)

Don't hesitate to ask if you still have problems.

**Comment by MontAle** [comment]
Oh thank you so much! I imagined that I could have solved editing the position in a file, but couldn't find that file in any place😂
Now I solved, thank you
