### ISSUE TITLE
Widgets stay selected after you focus out 

### ISSUE THREAD

**Issue by Philip-Scott** [spheras/desktopfolder#8]
Folders in Panels stay selected, and the text in notes still has the cursor blinking after clicking out of it

![screenshot from 2017-10-17 12 39 23](https://user-images.githubusercontent.com/10786508/31679904-39e49dec-b338-11e7-9c5e-a5045c6c4f72.png)

**Comment by spheras** [comment]
Right, we don't control yet the "focus lost" of the GTK window. It seems easy, I will capture the signal to change the color of the selected item, to something gray (similar to Files when you change the active window).

Thanks!

**Comment by spheras** [comment]
patch commited, the selected item now remains in gray when the panel is not active
