### ISSUE TITLE
Symlinks to network locations or external media have no icon until after restarting Desktop Folder

### ISSUE THREAD

**Issue by ernstki** [spheras/desktopfolder#82]
### Description
Symlinks to remote/external filesystems which are not present upon login have no icon when Desktop Folder is first launched. They continue to have no icon even after the target of the symlink becomes available, for example, by clicking on a bookmark in Files to reconnect with a network filesystem.

A restart of Desktop Folder is actually required to make the icons re-appear. The consequence is that if you have symlinks to network locations in your Desktop Folder (for example to `/var/run/user/<UID>/gvfs/<MOUNT_NAME>`), you can't set Desktop Folder to launch on startup.

While I did not test this to see if this problem occurs with an external HDD or USB flash drive, I _believe_ this problem will appear with symlinks that point to detached external filesystems as well.

### Steps to reproduce
1. Using elementaryOS Files, connect to a network location, _e.g._, an SMB/CIFS server or remote SSH server over SFTP
2. Create a symlink to the mounted remote filesystem somewhere using Files or the command line
3. Drag the symlink (that is, make a copy of it) from Files into a Desktop Folder folder view
4. Reboot (or disconnect the network location and restart Desktop Folder)
5. Note the missing icons for the symlinks

### Expected result
All icons are displayed, like so (screenshot showing Desktop Folder after killing and restarting it):

![desktop_folder-expected](https://user-images.githubusercontent.com/4009681/33799828-6fcecbb0-dd01-11e7-9f92-a1e4a84aded3.png)

Icons should remember what they are (folder, application, image) from the last invocation, and retain that icon, rather than displaying no icon when auto-detection of filetype fails (in this case, because the target of the link isn't present)

_—or—_

Desktop Folders folderviews should periodically refresh the icons. Probably not optimal.

_—optionally—_

Desktop Folders might show a small overlay icon (maybe a "no entry" symbol or a little "X") when the target of the symlink isn't present.

### Actual result
![desktop_folder-missing_icons](https://user-images.githubusercontent.com/4009681/33799830-70e145a0-dd01-11e7-8325-31ef3d2e9624.png)

### System Information
- OS: elementary OS 0.4 Loki
- Desktop Folder version: 1.0.2

### Terminal output

```
n/a
```

**Comment by spheras** [comment]
Thank you @ernstki for reporting!  I've made some changes to get the mount signal and recheck those icons for not existent files. Non existent files now get a default icon and a red cross over the icon and this is inmediatelly changed when a mounted file system is detected.  I'm submitting now, please, tell me the result if you can check it. Hope this solves the problem.

Thanks!

**Comment by ernstki** [comment]
Super, thanks. I can confirm it works as intended.
![desktop_folder-missing_icons-1 0 3](https://user-images.githubusercontent.com/4009681/33856685-e602f644-de96-11e7-9101-650079d6a64a.png)

I think caching the icon (from the last time the target of the symlink was available) is still a good idea, rather than using `text-x-generic`, but I'm sure you have lots of other issues to work through, so what you have is a perfectly reasonable solution for the time being.

If the red X's are bothering me enough, it might be just the motivation I need to finally learn something about Vala and Glib. ;)

**Comment by spheras** [comment]
:D... well, I agree the red X is a bit ugly, we can try to improve that and find a different way to indicate that the file is not available. Files do something similar what is done now with the red cross. Below image is a link to to a folder inside an unmounted drive:

![screenshot from 2017-12-12 08 11 16](https://user-images.githubusercontent.com/3862933/33871762-32c24bd8-df14-11e7-982b-3cf68c79a68f.png)

The difference is that it draws a forbidden and link icons instead a red cross. This is easy to modify.

Regarding caching the icon, it should be saved in a the .desktopfolder json file (image to b64 probably), and that would impair the application performance due to the .desktopfolder is generated a lot of times. So, I'm not sure about this.
