### ISSUE TITLE
Release v.1.0.3 - translations

### ISSUE THREAD

**Issue by spheras** [spheras/desktopfolder#85]
Finally, release v.1.0.3 is ready, I hope the new version will be published to the appcenter as soon as possible. There are a lot of changes that requires some updates to the translations files and that's why I require your help to update the translations po files if possible. I mention all of you here to check the possibility to update the translations you did in the past.  If it is not possible, don't worry, I'll try to do my best with google translator.

- French: @nvivant 
- Lithuanian: @welaq 
- Serbian: @pavlepiramida 
- Russian: @camellan 

Don't hesitate to ask me if you have any doubts.

Thanks in advance!

**Comment by camellan** [comment]
Great. I will try as soon as possible to finalize the translation into Russian.
