### ISSUE TITLE
Multiple folderdesktop properties panel

### ISSUE THREAD

**Issue by pavlepiramida** [spheras/desktopfolder#87]
Its pretty easy to recreate,
just click like mad dekstopfolder properties button

![peek 2017-12-15 16-43](https://user-images.githubusercontent.com/18991480/34049414-9f6923ce-e1b7-11e7-9ce5-cf51564c7dfe.gif)

Maybe throw in a check to see if properties panel is already open(drawn)?
Ive just noticed this issue tho :/

This is master branch build im using,I thought I'd mention it.

**Comment by spheras** [comment]
I made this dialog modal. Thanks again @pavlepiramida
