### ISSUE TITLE
Drag & drop breaks after dragging & dropping an item between panels

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#90]
### Description
Currently, if you Ctrl + Drag a file or folder, you get a helper which allows you to drag & drop the file or folder to another panel or app (like Files).

If you try to drag & drop a file or folder back into the panel it came from, it normally shows the "Link here" dialog, which is correct.

But if you then try and drag & drop a file or folder into another panel, this stops working.

Any panels you tried to drag & drop items that are already in it back into itself, plus the panel you tried to drag & drop an item from, will not allow you to drag & drop items back in to them. Instead, it shows the dialog that should show when you try to drag & drop a file or folder into the panel it's already in (the "Link here" dialog).

Trying to drag & drop panel items into the same panel for any panels that you didn't try doing so before makes Desktop Folder attempt to move the file into the same folder it came from, which obviously won't work.

You have to restart Desktop Folder in order to reset this behavior.

### Steps to reproduce
To drag & drop move a file: Hold Ctrl and hold down the left mouse on the file or folder from panel "1". Drag it slightly and the helper will appear. Let go of Ctrl.

1. ```killall com.github.spheras.desktopfolder``` and open Desktop Folder again.
2. Create three panels, named "1", "2" and "3". Create 1 uniquely named file or folder in "1" and "2".
3. Using the described drag & drop move method above, try to drag the item in panel "1" into the panel it's already in (panel "1"). This will correctly show the "Link here" dialog.
4. Do the same for the item in panel "2" (drag panel 2's item into the panel it's already in). This will also correctly show the "Link here" dialog.
5. Now drag & drop move the items in panel "1" and "2" into panel "3". Panel "3" should now have both items. This now triggers the bug.
4. Try dragging and dropping the items back into panel "1" or "2".

### Expected result
The item moves back into the panel.

### Actual result
The "Link here" dialog incorrectly shows for any panels you tried to do any drag & drop operation from.

For the panels that you tried to drag & drop from, they incorrectly always show the dialog for all drag & drop operations, while any panels you didn't try to drag & drop any items from stop showing it.

For the panels that you didn't try to drag & drop from, if you try to drag & drop an item into a panel that already contains it, it won't show the dialog and instead try to move the item into the folder that already contains it, which obviously won't work (see terminal output below).

![peek 2017-12-18 15-58](https://user-images.githubusercontent.com/10395308/34117602-141f093c-e414-11e7-9f4f-3287ad5a3c5b.gif)

### System Information
- OS: elementary OS 0.4 Loki (daily PPA)
- Desktop Folder version: master b8d79cacc3c16e84d9f7ab7ce834bec0d2283941

### Terminal output
```
$ env G_MESSAGES_DEBUG=all com.github.spheras.desktopfolder
(com.github.spheras.desktopfolder:9577): Gtk-DEBUG: Connecting to session manager
** (com.github.spheras.desktopfolder:9577): DEBUG: Application.vala:88: startup event
** (com.github.spheras.desktopfolder:9577): DEBUG: Application.vala:76: activate event
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderManager.vala:154: Monitoring: /home/aled/Desktop
** (com.github.spheras.desktopfolder:9577): DEBUG: DesktopManager.vala:70: DESKTOP SIZE CHANGED! -12,-10 - 1945,1105
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderManager.vala:154: Monitoring: /home/aled/Desktop/1
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderManager.vala:154: Monitoring: /home/aled/Desktop/3
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderManager.vala:154: Monitoring: /home/aled/Desktop/2
** (com.github.spheras.desktopfolder:9577): DEBUG: Application.vala:439: Monitoring: /home/aled/Desktop


(com.github.spheras.desktopfolder:9577): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.github.spheras.desktopfolder:9577): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(com.github.spheras.desktopfolder:9577): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** (com.github.spheras.desktopfolder:9577): DEBUG: DndHandler.vala:52: dnd_perform!!!
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:331: /home/aled/Desktop/1/1.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:377: moving /home/aled/Desktop/1/1.txt to /home/aled/Desktop/3
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderSettings.vala:277: Alert! doesnt exist: /home/aled/Desktop/1/1.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DndHandler.vala:52: dnd_perform!!!
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:331: /home/aled/Desktop/2/2.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:377: moving /home/aled/Desktop/2/2.txt to /home/aled/Desktop/3
** (com.github.spheras.desktopfolder:9577): DEBUG: FolderSettings.vala:277: Alert! doesnt exist: /home/aled/Desktop/2/2.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DndHandler.vala:52: dnd_perform!!!
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:331: /home/aled/Desktop/3/2.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:377: moving /home/aled/Desktop/3/2.txt to /home/aled/Desktop/3
Error: Target file exists
** (com.github.spheras.desktopfolder:9577): DEBUG: DndHandler.vala:52: dnd_perform!!!
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:331: /home/aled/Desktop/3/1.txt
** (com.github.spheras.desktopfolder:9577): DEBUG: DragNDrop.vala:377: moving /home/aled/Desktop/3/1.txt to /home/aled/Desktop/3
Error: Target file exists
```

**Comment by spheras** [comment]
I don't see yet why it is someway saving the last position of the file, or something like that. I did a change to avoid showing the link/cancel popup, and now you can move/copy to the original panel.  Could you take a look and comment if you think it is enough?

thanks!

**Comment by spheras** [comment]
Closing this issue with the changes made for the next version published. Please dont hesitate to reopen if necessary.
