### ISSUE TITLE
Multi-Monitor Problem

### ISSUE THREAD

**Issue by ar0ra1** [spheras/desktopfolder#96]
So, I connected my laptop to my screen and it was working fine.   
When i took out the hdmi cable, the icons have disappeared, now I can only see the icons and notes only when i connect it to the HDMI cable and only on the secondary screen and not on my `built-in` screen.

**Comment by spheras** [comment]
Hi @ar0ra1, thanks for reporting. This is something that should be solved with the last released version (1.0.5). Now you can select what strategy to follow regarding different resolutions. The default one is "STORE", which means, that you can have different possitions and sizes for the different resolutions. Each position and size will be saved for the concrete resolution.  You can see this configuration at the settings window -> General (right click on a panel).

Do you have the last versión of desktop-folder updated?

Anyway, you can always touch manually the .desktopfolder .desktopnote and so on.. These are json files and there you can see the x,y,width,height for each panel.

**Comment by ar0ra1** [comment]
Thank You!
